In [9]:
%pip install pandas numpy

import sys
from pathlib import Path
import pandas as pd
import numpy as np

print("Python:", sys.version)
print("Python executable:", sys.executable)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (3.0.5)
Requirement already satisfied: numpy in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Python executable: c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\python.exe
Pandas: 3.0.5
NumPy: 2.4.6

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# ============================================================
# CELL 2: PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(r"C:\projects\HACE_Financial_Sentiment_Analysis")

RAW_DIR = PROJECT_ROOT / "data" / "raw"
INTERIM_DIR = PROJECT_ROOT / "data" / "interim"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

FIQA_DIR = RAW_DIR / "fiqa"
TWITTER_DIR = RAW_DIR / "twitter"
PHRASEBANK_DIR = RAW_DIR / "phrasebank"
FINANCE_NEWS_DIR = RAW_DIR / "finance_news"


# Create output directories
INTERIM_DIR.mkdir(
    parents=True,
    exist_ok=True
)

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print("Project Root :", PROJECT_ROOT)
print("Raw Data     :", RAW_DIR)
print("Interim      :", INTERIM_DIR)
print("Processed    :", PROCESSED_DIR)

Project Root : \home\amankhanduja\NLP_Project\HACE
Raw Data     : \home\amankhanduja\NLP_Project\HACE\data\raw
Interim      : \home\amankhanduja\NLP_Project\HACE\data\interim
Processed    : \home\amankhanduja\NLP_Project\HACE\data\processed

In [11]:
# ============================================================
# CELL 3: VERIFY RAW DATA
# ============================================================

datasets = {
    "FiQA": FIQA_DIR,
    "Twitter": TWITTER_DIR,
    "FinancialPhraseBank": PHRASEBANK_DIR,
    "Finance News": FINANCE_NEWS_DIR
}


for name, directory in datasets.items():

    print("\n" + "=" * 50)
    print(name)
    print("=" * 50)

    if not directory.exists():

        print("❌ Directory does not exist:")
        print(directory)
        continue

    files = list(directory.iterdir())

    if not files:

        print("⚠ Directory is empty")
        continue

    for file in files:

        if file.is_file():

            size_mb = (
                file.stat().st_size /
                (1024 * 1024)
            )

            print(
                f"✓ {file.name:35} "
                f"{size_mb:.2f} MB"
            )

==================================================
FiQA
==================================================
❌ Directory does not exist:
\home\amankhanduja\NLP_Project\HACE\data\raw\fiqa

==================================================
Twitter
==================================================
❌ Directory does not exist:
\home\amankhanduja\NLP_Project\HACE\data\raw\twitter

==================================================
FinancialPhraseBank
==================================================
❌ Directory does not exist:
\home\amankhanduja\NLP_Project\HACE\data\raw\phrasebank

==================================================
Finance News
==================================================
❌ Directory does not exist:
\home\amankhanduja\NLP_Project\HACE\data\raw\finance_news

In [12]:
# ============================================================
# CELL 4: LOAD FiQA
# ============================================================

fiqa_train = pd.read_csv(
    FIQA_DIR / "train.csv"
)

fiqa_test = pd.read_csv(
    FIQA_DIR / "test.csv"
)

fiqa_valid = pd.read_csv(
    FIQA_DIR / "valid.csv"
)


print("FiQA Train:", fiqa_train.shape)
print("FiQA Test :", fiqa_test.shape)
print("FiQA Valid:", fiqa_valid.shape)

print("\nColumns:")
print(fiqa_train.columns.tolist())

print("\nSample:")
display(fiqa_train.head())

FileNotFoundError: [Errno 2] No such file or directory: '\\home\\amankhanduja\\NLP_Project\\HACE\\data\\raw\\fiqa\\train.csv'

In [ ]:
# ============================================================
# CELL 5: LOAD TWITTER FINANCIAL NEWS
# ============================================================

twitter_train = pd.read_csv(
    TWITTER_DIR / "train.csv"
)

twitter_valid = pd.read_csv(
    TWITTER_DIR / "validation.csv"
)


print("Twitter Train:", twitter_train.shape)
print("Twitter Valid:", twitter_valid.shape)

print("\nColumns:")
print(twitter_train.columns.tolist())

print("\nSample:")
display(twitter_train.head())

Twitter Train: (9543, 2)
Twitter Valid: (2388, 2)

Columns:
['text', 'label']

Sample:

                                                text  label
0  $BYND - JPMorgan reels in expectations on Beyo...      0
1  $CCL $RCL - Nomura points to bookings weakness...      0
2  $CX - Cemex cut at Credit Suisse, J.P. Morgan ...      0
3  $ESS: BTIG Research cuts to Neutral https://t....      0
4  $FNKO - Funko slides after Piper Jaffray PT cu...      0

In [ ]:
# ============================================================
# CELL 6: LOAD FINANCIALPHRASEBANK
# ============================================================

phrasebank_file = (
    PHRASEBANK_DIR /
    "Sentences_AllAgree.txt"
)


print("File:", phrasebank_file)


with open(
    phrasebank_file,
    "r",
    encoding="latin-1"
) as f:

    phrasebank_lines = f.readlines()


print(
    "Number of lines:",
    len(phrasebank_lines)
)


print("\nFirst 5 lines:")

for line in phrasebank_lines[:5]:

    print(line.strip())

File: /home/amankhanduja/NLP_Project/HACE/data/raw/phrasebank/Sentences_AllAgree.txt
Number of lines: 2264

First 5 lines:
According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .@neutral
For the last quarter of 2010 , Componenta 's net sales doubled to EUR131m from EUR76m for the same period a year earlier , while it moved to a zero pre-tax profit from a pre-tax loss of EUR7m .@positive
In the third quarter of 2010 , net sales increased by 5.2 % to EUR 205.5 mn , and operating profit by 34.9 % to EUR 23.5 mn .@positive
Operating profit rose to EUR 13.1 mn from EUR 8.7 mn in the corresponding period in 2007 representing 7.7 % of net sales .@positive
Operating profit totalled EUR 21.1 mn , up from EUR 18.6 mn in 2007 , representing 9.7 % of net sales .@positive

In [ ]:
# ============================================================
# CELL 7: LOAD KAGGLE FINANCE NEWS
# ============================================================

finance_news_files = list(
    FINANCE_NEWS_DIR.glob("*.csv")
)

print("CSV files found:")

for file in finance_news_files:
    print(" -", file.name)


if not finance_news_files:

    raise FileNotFoundError(
        "No CSV file found in finance_news directory."
    )


# If there is only one CSV, load it
finance_news = pd.read_csv(
    finance_news_files[0]
)


print("\nShape:")
print(finance_news.shape)

print("\nColumns:")
print(finance_news.columns.tolist())

print("\nSample:")
display(finance_news.head())

CSV files found:
 - dataset.csv

Shape:
(32583, 2)

Columns:
['sentiment', 'text']

Sample:

  sentiment                                               text
0  positive  All banks, lending institutions may allow a th...
1   neutral                              Not so fast, Drake...
2  positive  FNF - ong  19.43. Trailing Stop  21.04 from 6 ...
3  positive  Dow opens down almost 500 points after China h...
4  positive  U.S. weekly active oil-rig count edges up by 1...

In [ ]:
# ============================================================
# CELL 8: INSPECT LABELS
# ============================================================

print("=" * 60)
print("FiQA LABELS")
print("=" * 60)

print(fiqa_train.columns.tolist())

for column in fiqa_train.columns:

    print(
        f"\n{column}:"
    )

    print(
        fiqa_train[column]
        .value_counts(dropna=False)
        .head(20)
    )


print("\n" + "=" * 60)
print("TWITTER LABELS")
print("=" * 60)

for column in twitter_train.columns:

    print(
        f"\n{column}:"
    )

    print(
        twitter_train[column]
        .value_counts(dropna=False)
        .head(20)
    )


print("\n" + "=" * 60)
print("FINANCE NEWS LABELS")
print("=" * 60)

for column in finance_news.columns:

    print(
        f"\n{column}:"
    )

    print(
        finance_news[column]
        .value_counts(dropna=False)
        .head(20)
    )

============================================================
FiQA LABELS
============================================================
['_id', 'sentence', 'target', 'aspect', 'score', 'type']

_id:
_id
241     3
1077    3
1663    3
1360    3
345     2
1735    2
1635    2
1079    2
32      2
1356    2
49      2
444     2
1217    2
1122    2
1349    2
1065    2
477     2
358     2
1143    2
1712    2
Name: count, dtype: int64

sentence:
sentence
London open: Taylor Wimpey and Ashtead drive markets higher, Barclays falls                                             3
Sainsbury's, Asda, Tesco and Morrisons will all cut petrol prices as oil falls ...                                      3
Goldman Sachs, Barclays, HSBC downplay Brexit threat                                                                    3
Balfour Beatty plc Set To Reinstate Dividend (And Rival National Grid plc And Centrica PLC Once More?)                  3
Shell challenges Exxon dominance with 47 billion-pound bid for BG                                                       2
Should you buy Associated British Foods plc, Great Portland Estates plc and Dunelm Group plc following today's news?    2
Sainsbury CFO Rogers to Replace Home Retail CEO Walden                                                                  2
EU drops Shell, BP, Statoil from ethanol benchmark investigation                                                        2
Tesco sells Blinkbox and broadband service to TalkTalk                                                                  2
News FeedFTSE 100 movers: LSE surges as ICE says mulling offer; Ashtead and Barclays tank                               2
Teva: FDA Approves Generic Version of AstraZeneca Heartburn Drug                                                        2
PRESS: Serco Set To Appoint Roy Gardner, Ex-Centrica, As Chairman - FT                                                  2
Shire share price under pressure after $32bn Baxalta deal                                                               2
ITV share price jumps on report of Comcast's NBCUniversal bidding to takeover ...                                       2
Barclays appoints JPMorgan's Paul Compton as new COO                                                                    2
StanChart and RBS struggle in Bank of England stress tests                                                              2
Centrica extends gas deals with Gazprom, Statoil                                                                        2
Diageo receives reports from United Spirits on financial irregularities involving ...                                   2
Standard Chartered, RBS Escape Capital Raising in Stress Test                                                           2
The Coca-Cola Company and Coca-Cola FEMSA to Acquire AdeS Soy-Based Beverage Business From Unilever                     2
Name: count, dtype: int64

target:
target
AAPL                  47
SPY                   27
Tesco                 23
FB                    12
AstraZeneca           12
Shell                 11
BBRY                  11
SABMiller             10
TSLA                  10
LSE                    9
AMZN                   8
Shire                  7
NFLX                   7
Morrisons              7
RBS                    7
Barclays               6
Standard Chartered     6
YHOO                   6
Friends Life           5
Royal Mail             5
Name: count, dtype: int64

aspect:
aspect
Stock/Price Action/Bullish                     70
Stock/Technical Analysis                       62
Stock/Price Action                             60
Stock/Price Action/Bullish/Bullish Behavior    52
Stock/Price Action/Bearish                     38
Corporate/Sales                                35
Corporate/M&A/M&A                              34
Stock/Price Action/Bearish/Bearish Behavior    32
Stock/Price Action/Bullish/Bull Position       28
Corporate/Dividend Policy                      27
Corporate/Appointment                          17
Corporate/Risks                                17
Corporate/Sales/Deal                           14
Stock/Price Action/Volatility/Short Selling    12
Corporate/Rumors/Rumors                        11
Stock/Signal/Buy Signal                        11
Market/Market                                  10
Stock/Technical Analysis/Breakout               9
Stock/Signal/Sell Signal                        9
Corporate/Regulatory                            9
Name: count, dtype: int64

score:
score
 0.000    12
 0.385     5
 0.437     4
 0.394     4
 0.259     4
 0.526     4
 0.308     4
 0.365     4
 0.396     4
 0.143     4
 0.492     4
 0.348     3
-0.390     3
 0.395     3
 0.372     3
 0.284     3
 0.316     3
 0.144     3
 0.195     3
 0.495     3
Name: count, dtype: int64

type:
type
post        473
headline    349
Name: count, dtype: int64

============================================================
TWITTER LABELS
============================================================

text:
text
$BYND - JPMorgan reels in expectations on Beyond Meat https://t.co/bd0xbFGjkT                                                                   1
In its 2020 equity outlook, Goldman predicts the S&P 500 will rise by 5% to 3250 in early 2020. "However, rising po… https://t.co/3e9Zj6q3oQ    1
Indian sugar exports poised to hit record 5 million tonnes this year                                                                            1
Initial U.S. jobless claims drop 15,000 to 202,000                                                                                              1
Irish demand for social benefits soars as coronavirus bites #economy #MarketScreener https://t.co/T9hGEfJy23 https://t.co/iM1IVUPF3a            1
January jobs report: Economy adds 225,000 payrolls, unemployment rate ticks up to 3.6%                                                          1
Japan Edges Closer to Ratifying Trump’s Phase One Trade Deal                                                                                    1
Job Openings in U.S. Unexpectedly Rose in October to 7.3 Million                                                                                1
Job Openings Smash Expectations In Delayed JOLTS Report  https://t.co/7tHGcCcxei                                                                1
Jobless claims hit multi-year low                                                                                                               1
JPMorgan's Jamie Dimon said he expects to see a phase-one trade deal between the U.S. and China https://t.co/PzVxE4Cybv                         1
Kudlow calls U.S.-China deal 'close' as talks in 'intense' phase https://t.co/Nv9zq3zqVX                                                        1
Kudlow Says Xi Reassured Trump Trade Purchases Goal Will Be Met                                                                                 1
Kudlow sees no signs U.S. economy is nearing end of the cycle                                                                                   1
Leafly Jobs Report: Cannabis is the fastest-growing American industry, surpassing 240,000 jobs                                                  1
Lloyds Banking : Value of UK exports to non-EU countries rises in 2019 #LloydsBanking #economy #MarketScreener… https://t.co/s6TyiRYCVQ         1
Mild weather boosts U.S. job growth; unemployment rate rises                                                                                    1
Increase in October sales raised to 0.4% from 0.3%                                                                                              1
IHS Markit reduces global recession probability to 1 in 5; sees 'green shoots' sprouting in 2020                                                1
Economist Slok sees no U.S. recession, "benign" markets in 2020 https://t.co/RlzUHUaie1 https://t.co/6DPYzKO1bo                                 1
Name: count, dtype: int64

label:
label
2    6178
1    1923
0    1442
Name: count, dtype: int64

============================================================
FINANCE NEWS LABELS
============================================================

sentiment:
sentiment
positive    10861
neutral     10861
negative    10861
Name: count, dtype: int64

text:
text
News Highlights : Top Energy News of the Day #WTI #Stock #MarketScreener                                                15
NaN                                                                                                                     14
$COMDX: Metals Settlement Prices                                                                                        12
$COMDX: Energy Settlement Prices                                                                                        11
$WIRES: On The Wires                                                                                                     9
$XLE: Sector Briefing: Energy                                                                                            5
On the hour                                                                                                              5
$BONDX: Overnight Treasury Market Summary                                                                                4
$BONDX: Treasury Market Summary                                                                                          4
Marc Trimble                                                                                                             3
While market strain triggered by the coronavirus pandemic has eased since the Federal Reserve's historic interventi…     3
$SCANX: Today's biggest % gainers/losers                                                                                 3
News Highlights : Top Global Markets News of the Day #NewsHighlights #economy #MarketScreener…                           3
Gold Falls After Strong Jobless Report #Silver #Stock #MarketScreener                                                    3
U.S. economy is in a contraction, says Larry Kudlow, adding that it could reopen in four to eight weeks                  2
Gold Edges Lower With Investors Eyeing Economic Data #Silver #Stock #MarketScreener                                      2
With milk prices plunging to lows, dairy farmers are dumping the product to curb an oversupply during the…               2
$SCANX: Today's most active stocks                                                                                       2
The number of U.S. homeowners who have stopped making mortgage payments is surging                                       2
Investors should prepare for a coronavirus-induced 'vicious spiral' more than twice as bad as the financial crisis,…     2
Name: count, dtype: int64

In [ ]:
# ============================================================
# CELL 9 — MISSING VALUE ANALYSIS
# ============================================================

def missing_report(df, name):
    print("=" * 60)
    print(name)
    print("=" * 60)

    report = pd.DataFrame({
        "missing_count": df.isnull().sum(),
        "missing_percent": (
            df.isnull().mean() * 100
        ).round(2)
    })

    display(report)


missing_report(fiqa_train, "FiQA Train")
missing_report(twitter_train, "Twitter Train")
missing_report(finance_news, "Finance News")

print("=" * 60)
print("FINANCIALPHRASEBANK")
print("=" * 60)

print("Total lines:", len(phrasebank_lines))

empty_lines = [
    line for line in phrasebank_lines
    if not line.strip()
]

print("Empty lines:", len(empty_lines))

============================================================
FiQA Train
============================================================

          missing_count  missing_percent
_id                   0              0.0
sentence              0              0.0
target                0              0.0
aspect                0              0.0
score                 0              0.0
type                  0              0.0

============================================================
Twitter Train
============================================================

       missing_count  missing_percent
text               0              0.0
label              0              0.0

============================================================
Finance News
============================================================

           missing_count  missing_percent
sentiment              0             0.00
text                  14             0.04

============================================================
FINANCIALPHRASEBANK
============================================================
Total lines: 2264
Empty lines: 0

In [ ]:
# ============================================================
# CELL 10 — DUPLICATE ANALYSIS
# ============================================================

def duplicate_report(df, name, text_column):
    
    print("=" * 60)
    print(name)
    print("=" * 60)

    total = len(df)

    duplicates = df[text_column].duplicated().sum()

    unique = df[text_column].nunique()

    print("Total rows      :", total)
    print("Unique texts    :", unique)
    print("Duplicate rows  :", duplicates)
    print(
        "Duplicate %     :",
        round((duplicates / total) * 100, 2),
        "%"
    )


# IMPORTANT:
# Use the actual text-column names you discovered in Cell 8.

In [ ]:
duplicate_report(
    fiqa_train,
    "FiQA Train",
    "sentence"
)

duplicate_report(
    twitter_train,
    "Twitter Train",
    "text"
)

duplicate_report(
    finance_news,
    "Finance News",
    "text"
)

============================================================
FiQA Train
============================================================
Total rows      : 822
Unique texts    : 770
Duplicate rows  : 52
Duplicate %     : 6.33 %
============================================================
Twitter Train
============================================================
Total rows      : 9543
Unique texts    : 9543
Duplicate rows  : 0
Duplicate %     : 0.0 %
============================================================
Finance News
============================================================
Total rows      : 32583
Unique texts    : 32410
Duplicate rows  : 172
Duplicate %     : 0.53 %

In [ ]:
# ============================================================
# CELL 11 — TEXT STATISTICS
# ============================================================

def text_statistics(df, name, text_column):

    text_lengths = (
        df[text_column]
        .astype(str)
        .str.split()
        .str.len()
    )

    print("=" * 60)
    print(name)
    print("=" * 60)

    print("Number of samples :", len(df))
    print("Average words     :", round(text_lengths.mean(), 2))
    print("Median words      :", round(text_lengths.median(), 2))
    print("Maximum words     :", text_lengths.max())
    print("Minimum words     :", text_lengths.min())


# Example:
# text_statistics(fiqa_train, "FiQA", "sentence")
# text_statistics(twitter_train, "Twitter", "text")
# text_statistics(finance_news, "Finance News", "text")

In [ ]:
# ============================================================
# CELL 12 — INSPECT FINANCIALPHRASEBANK FORMAT
# ============================================================

for i, line in enumerate(phrasebank_lines[:10]):

    print(f"{i}: {repr(line)}")

0: 'According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .@neutral\n'
1: "For the last quarter of 2010 , Componenta 's net sales doubled to EUR131m from EUR76m for the same period a year earlier , while it moved to a zero pre-tax profit from a pre-tax loss of EUR7m .@positive\n"
2: 'In the third quarter of 2010 , net sales increased by 5.2 % to EUR 205.5 mn , and operating profit by 34.9 % to EUR 23.5 mn .@positive\n'
3: 'Operating profit rose to EUR 13.1 mn from EUR 8.7 mn in the corresponding period in 2007 representing 7.7 % of net sales .@positive\n'
4: 'Operating profit totalled EUR 21.1 mn , up from EUR 18.6 mn in 2007 , representing 9.7 % of net sales .@positive\n'
5: 'Finnish Talentum reports its operating profit increased to EUR 20.5 mn in 2005 from EUR 9.3 mn in 2004 , and net sales totaled EUR 103.3 mn , up from EUR 96.4 mn .@positive\n'
6: "Clothing retail chain Sepp+ñl+ñ 's sales increased by 8 % to EUR 155.2 mn , and operating profit rose to EUR 31.1 mn from EUR 17.1 mn in 2004 .@positive\n"
7: 'Consolidated net sales increased 16 % to reach EUR74 .8 m , while operating profit amounted to EUR0 .9 m compared to a loss of EUR0 .7 m in the prior year period .@positive\n'
8: 'Foundries division reports its sales increased by 9.7 % to EUR 63.1 mn from EUR 57.5 mn in the corresponding period in 2006 , and sales of the Machine Shop division increased by 16.4 % to EUR 41.2 mn from EUR 35.4 mn in the corresponding period in 2006 .@positive\n'
9: "HELSINKI ( AFX ) - Shares closed higher , led by Nokia after it announced plans to team up with Sanyo to manufacture 3G handsets , and by Nokian Tyres after its fourth-quarter earnings report beat analysts ' expectations , dealers said .@positive\n"

In [ ]:
# ============================================================
# CELL 13 — LABEL DISTRIBUTIONS
# ============================================================

def label_distribution(df, name, label_column):

    print("=" * 60)
    print(name)
    print("=" * 60)

    counts = df[label_column].value_counts(
        dropna=False
    )

    percentages = (
        df[label_column]
        .value_counts(
            normalize=True,
            dropna=False
        )
        .mul(100)
        .round(2)
    )

    report = pd.DataFrame({
        "count": counts,
        "percentage": percentages
    })

    display(report)

In [ ]:
# ============================================================
# CELL 14 — NORMALIZE FiQA
# ============================================================

print("=" * 60)
print("NORMALIZING FiQA")
print("=" * 60)

# ------------------------------------------------------------
# FiQA schema
# ------------------------------------------------------------
# _id
# sentence
# target
# aspect
# score
# type
#
# We use:
# sentence -> text
# score    -> sentiment
# ------------------------------------------------------------


# Create normalized dataframe
fiqa_normalized = fiqa_train[
    ["sentence", "score"]
].copy()


# Rename columns
fiqa_normalized.columns = [
    "text",
    "score"
]


# Add source
fiqa_normalized["source"] = "fiqa"


# ------------------------------------------------------------
# Clean text
# ------------------------------------------------------------

fiqa_normalized["text"] = (
    fiqa_normalized["text"]
    .astype(str)
    .str.strip()
)


# Remove empty text
fiqa_normalized = fiqa_normalized[
    (fiqa_normalized["text"] != "") &
    (fiqa_normalized["text"] != "nan")
].copy()


# ------------------------------------------------------------
# Convert FiQA continuous score
# to common 3-class sentiment
#
# score < -0.1       -> negative = 0
# -0.1 <= score <= .1 -> neutral = 1
# score > 0.1        -> positive = 2
# ------------------------------------------------------------

def fiqa_score_to_label(score):

    if score < -0.1:
        return 0

    elif score <= 0.1:
        return 1

    else:
        return 2


fiqa_normalized["label"] = (
    fiqa_normalized["score"]
    .apply(fiqa_score_to_label)
)


# ------------------------------------------------------------
# Remove original score from final unified schema
# ------------------------------------------------------------

fiqa_normalized = fiqa_normalized[
    ["text", "label", "source"]
].reset_index(drop=True)


# ------------------------------------------------------------
# Verification
# ------------------------------------------------------------

print("\nShape:")
print(fiqa_normalized.shape)

print("\nColumns:")
print(fiqa_normalized.columns.tolist())

print("\nLabel distribution:")
print(
    fiqa_normalized["label"]
    .value_counts()
    .sort_index()
)

print("\nSource distribution:")
print(
    fiqa_normalized["source"]
    .value_counts()
)

print("\nSample:")
display(
    fiqa_normalized.head(10)
)

============================================================
NORMALIZING FiQA
============================================================

Shape:
(822, 3)

Columns:
['text', 'label', 'source']

Label distribution:
label
0    237
1     72
2    513
Name: count, dtype: int64

Source distribution:
source
fiqa    822
Name: count, dtype: int64

Sample:

                                                text  label source
0  Royal Mail chairman Donald Brydon set to step ...      0   fiqa
1     Slump in Weir leads FTSE down from record high      0   fiqa
2  AstraZeneca wins FDA approval for key new lung...      2   fiqa
3  UPDATE 1-Lloyds to cut 945 jobs as part of 3-y...      0   fiqa
4  Standard Chartered Shifts Emerging-Markets Str...      0   fiqa
5  AstraZeneca's Lung Cancer Drug Tagrisso Gets F...      2   fiqa
6  Severn Trent share price rises as first half p...      2   fiqa
7  Glencore sees Tripoli-based NOC as sole legal ...      1   fiqa
8  Lloyds to cut 945 jobs as part of three-year r...      0   fiqa
9      AstraZeneca to Buy ZS Pharma for $2.7 Billion      2   fiqa

In [ ]:
# ============================================================
# CELL 15 — NORMALIZE ALL FiQA SPLITS
# ============================================================

def normalize_fiqa(df, split_name):

    result = df[
        ["sentence", "score"]
    ].copy()

    result.columns = [
        "text",
        "score"
    ]

    result["source"] = "fiqa"

    # Clean text
    result["text"] = (
        result["text"]
        .astype(str)
        .str.strip()
    )

    # Remove empty text
    result = result[
        (result["text"] != "") &
        (result["text"] != "nan")
    ].copy()

    # Convert continuous FiQA score → 3 classes
    result["label"] = result["score"].apply(
        fiqa_score_to_label
    )

    # Final schema
    result = result[
        ["text", "label", "source"]
    ].reset_index(drop=True)

    print(
        f"{split_name:10} → {result.shape}"
    )

    return result


# Normalize each split separately

fiqa_train_normalized = normalize_fiqa(
    fiqa_train,
    "Train"
)

fiqa_valid_normalized = normalize_fiqa(
    fiqa_valid,
    "Validation"
)

fiqa_test_normalized = normalize_fiqa(
    fiqa_test,
    "Test"
)

Train      → (822, 3)
Validation → (117, 3)
Test       → (234, 3)

In [ ]:
# ============================================================
# CELL 16 — FiQA LABEL VERIFICATION
# ============================================================

fiqa_splits = {
    "Train": fiqa_train_normalized,
    "Validation": fiqa_valid_normalized,
    "Test": fiqa_test_normalized
}


for name, df in fiqa_splits.items():

    print("\n" + "=" * 50)
    print(f"FiQA {name}")
    print("=" * 50)

    print("Shape:", df.shape)

    print("\nLabels:")
    print(
        df["label"]
        .value_counts()
        .sort_index()
    )

    print("\nMissing:")
    print(
        df.isnull().sum()
    )

    print("\nSample:")
    display(df.head(3))

==================================================
FiQA Train
==================================================
Shape: (822, 3)

Labels:
label
0    237
1     72
2    513
Name: count, dtype: int64

Missing:
text      0
label     0
source    0
dtype: int64

Sample:

                                                text  label source
0  Royal Mail chairman Donald Brydon set to step ...      0   fiqa
1     Slump in Weir leads FTSE down from record high      0   fiqa
2  AstraZeneca wins FDA approval for key new lung...      2   fiqa

==================================================
FiQA Validation
==================================================
Shape: (117, 3)

Labels:
label
0    42
1     9
2    66
Name: count, dtype: int64

Missing:
text      0
label     0
source    0
dtype: int64

Sample:

                                                text  label source
0  S&P downgrades Barclays and RBS on government ...      0   fiqa
1  Irish housebuilder Cairn Homes plans London li...      2   fiqa
2               Arm slammed by handset sales outlook      0   fiqa

==================================================
FiQA Test
==================================================
Shape: (234, 3)

Labels:
label
0     84
1     12
2    138
Name: count, dtype: int64

Missing:
text      0
label     0
source    0
dtype: int64

Sample:

                                                text  label source
0  Britain's FTSE steadies, supported by Dixons C...      2   fiqa
1  Glaxo's ViiV Healthcare Signs China Manufactur...      2   fiqa
2   AstraZeneca sells Caprelsa rights to Sanofi unit      2   fiqa

In [ ]:
# ============================================================
# CELL 18 — NORMALIZE TWITTER
# ============================================================

TWITTER_TEXT_COLUMN = "text"
TWITTER_LABEL_COLUMN = "label"


def normalize_twitter(df, split_name):

    result = df[
        [
            TWITTER_TEXT_COLUMN,
            TWITTER_LABEL_COLUMN
        ]
    ].copy()

    result.columns = [
        "text",
        "label"
    ]

    result["source"] = "twitter"

    # Clean text
    result["text"] = (
        result["text"]
        .astype(str)
        .str.strip()
    )

    # Remove empty text
    result = result[
        (result["text"] != "") &
        (result["text"] != "nan")
    ].copy()

    # --------------------------------------------------------
    # Handle labels
    # --------------------------------------------------------

    # If labels are already numeric 0/1/2
    if pd.api.types.is_numeric_dtype(
        result["label"]
    ):

        result["label"] = (
            result["label"]
            .astype(int)
        )

    # If labels are strings
    else:

        result["label"] = (
            result["label"]
            .astype(str)
            .str.lower()
            .str.strip()
            .map({
                "negative": 0,
                "neutral": 1,
                "positive": 2
            })
        )

    # Check for invalid labels
    invalid = result[
        ~result["label"].isin([0, 1, 2])
    ]

    if len(invalid) > 0:

        print(
            f"⚠ {split_name}: "
            f"{len(invalid)} invalid labels found"
        )

        print(
            invalid["label"]
            .value_counts(dropna=False)
        )

        raise ValueError(
            "Twitter label mapping needs to be checked."
        )

    result["label"] = (
        result["label"]
        .astype(int)
    )

    return result[
        ["text", "label", "source"]
    ].reset_index(drop=True)


twitter_train_normalized = normalize_twitter(
    twitter_train,
    "Train"
)

twitter_valid_normalized = normalize_twitter(
    twitter_valid,
    "Validation"
)


print(
    "Twitter Train:",
    twitter_train_normalized.shape
)

print(
    "Twitter Validation:",
    twitter_valid_normalized.shape
)

Twitter Train: (9543, 3)
Twitter Validation: (2388, 3)

In [ ]:
# ============================================================
# CELL 19 — VERIFY AND SAVE
# ============================================================

twitter_splits = {
    "Train": twitter_train_normalized,
    "Validation": twitter_valid_normalized
}


print("=" * 60)
print("TWITTER VERIFICATION")
print("=" * 60)


for name, df in twitter_splits.items():

    print("\n" + "-" * 50)
    print(f"Twitter {name}")

    print("Shape:", df.shape)

    print("\nLabels:")
    print(
        df["label"]
        .value_counts()
        .sort_index()
    )

    print("\nMissing values:")
    print(
        df.isnull().sum()
    )


# ============================================================
# SAVE FiQA
# ============================================================

fiqa_train_normalized.to_csv(
    PROCESSED_DIR / "fiqa_train.csv",
    index=False
)

fiqa_valid_normalized.to_csv(
    PROCESSED_DIR / "fiqa_validation.csv",
    index=False
)

fiqa_test_normalized.to_csv(
    PROCESSED_DIR / "fiqa_test.csv",
    index=False
)


# ============================================================
# SAVE TWITTER
# ============================================================

twitter_train_normalized.to_csv(
    PROCESSED_DIR / "twitter_train.csv",
    index=False
)

twitter_valid_normalized.to_csv(
    PROCESSED_DIR / "twitter_validation.csv",
    index=False
)


print("\n✓ FiQA normalized datasets saved")
print("✓ Twitter normalized datasets saved")

print("\nOutput directory:")
print(PROCESSED_DIR)

============================================================
TWITTER VERIFICATION
============================================================

--------------------------------------------------
Twitter Train
Shape: (9543, 3)

Labels:
label
0    1442
1    1923
2    6178
Name: count, dtype: int64

Missing values:
text      0
label     0
source    0
dtype: int64

--------------------------------------------------
Twitter Validation
Shape: (2388, 3)

Labels:
label
0     347
1     475
2    1566
Name: count, dtype: int64

Missing values:
text      0
label     0
source    0
dtype: int64

✓ FiQA normalized datasets saved
✓ Twitter normalized datasets saved

Output directory:
/home/amankhanduja/NLP_Project/HACE/data/processed

In [ ]:
# ============================================================
# CELL 19 — VERIFY AND SAVE
# ============================================================

twitter_splits = {
    "Train": twitter_train_normalized,
    "Validation": twitter_valid_normalized
}


print("=" * 60)
print("TWITTER VERIFICATION")
print("=" * 60)


for name, df in twitter_splits.items():

    print("\n" + "-" * 50)
    print(f"Twitter {name}")

    print("Shape:", df.shape)

    print("\nLabels:")
    print(
        df["label"]
        .value_counts()
        .sort_index()
    )

    print("\nMissing values:")
    print(
        df.isnull().sum()
    )


# ============================================================
# SAVE FiQA
# ============================================================

fiqa_train_normalized.to_csv(
    PROCESSED_DIR / "fiqa_train.csv",
    index=False
)

fiqa_valid_normalized.to_csv(
    PROCESSED_DIR / "fiqa_validation.csv",
    index=False
)

fiqa_test_normalized.to_csv(
    PROCESSED_DIR / "fiqa_test.csv",
    index=False
)


# ============================================================
# SAVE TWITTER
# ============================================================

twitter_train_normalized.to_csv(
    PROCESSED_DIR / "twitter_train.csv",
    index=False
)

twitter_valid_normalized.to_csv(
    PROCESSED_DIR / "twitter_validation.csv",
    index=False
)


print("\n✓ FiQA normalized datasets saved")
print("✓ Twitter normalized datasets saved")

print("\nOutput directory:")
print(PROCESSED_DIR)

============================================================
TWITTER VERIFICATION
============================================================

--------------------------------------------------
Twitter Train
Shape: (9543, 3)

Labels:
label
0    1442
1    1923
2    6178
Name: count, dtype: int64

Missing values:
text      0
label     0
source    0
dtype: int64

--------------------------------------------------
Twitter Validation
Shape: (2388, 3)

Labels:
label
0     347
1     475
2    1566
Name: count, dtype: int64

Missing values:
text      0
label     0
source    0
dtype: int64

✓ FiQA normalized datasets saved
✓ Twitter normalized datasets saved

Output directory:
/home/amankhanduja/NLP_Project/HACE/data/processed

In [ ]:
# ============================================================
# CELL 21 — NORMALIZE FINANCIALPHRASEBANK
# ============================================================

phrasebank_records = []

for line in phrasebank_lines:

    line = line.strip()

    if not line:
        continue

    # Sentence and sentiment are separated by @
    parts = line.rsplit("@", 1)

    if len(parts) != 2:
        continue

    text, sentiment = parts

    text = text.strip()
    sentiment = sentiment.strip().lower()

    phrasebank_records.append({
        "text": text,
        "sentiment": sentiment
    })


phrasebank_normalized = pd.DataFrame(
    phrasebank_records
)


print("Parsed rows:", phrasebank_normalized.shape)

print("\nOriginal labels:")
print(
    phrasebank_normalized["sentiment"]
    .value_counts()
)


# ------------------------------------------------------------
# Map sentiment → common HACE labels
# ------------------------------------------------------------

phrasebank_normalized["label"] = (
    phrasebank_normalized["sentiment"]
    .map({
        "negative": 0,
        "neutral": 1,
        "positive": 2
    })
)


# Check invalid labels
invalid = phrasebank_normalized[
    phrasebank_normalized["label"].isna()
]

print("\nInvalid labels:", len(invalid))

if len(invalid) > 0:
    print(invalid["sentiment"].value_counts())


# Remove sentiment text column
phrasebank_normalized = (
    phrasebank_normalized[
        ["text", "label"]
    ]
    .copy()
)

phrasebank_normalized["source"] = "phrasebank"

phrasebank_normalized["label"] = (
    phrasebank_normalized["label"]
    .astype(int)
)

phrasebank_normalized = (
    phrasebank_normalized
    .reset_index(drop=True)
)


print("\nFinal shape:")
print(phrasebank_normalized.shape)

display(
    phrasebank_normalized.head()
)

Parsed rows: (2264, 2)

Original labels:
sentiment
neutral     1391
positive     570
negative     303
Name: count, dtype: int64

Invalid labels: 0

Final shape:
(2264, 3)

                                                text  label      source
0  According to Gran , the company has no plans t...      1  phrasebank
1  For the last quarter of 2010 , Componenta 's n...      2  phrasebank
2  In the third quarter of 2010 , net sales incre...      2  phrasebank
3  Operating profit rose to EUR 13.1 mn from EUR ...      2  phrasebank
4  Operating profit totalled EUR 21.1 mn , up fro...      2  phrasebank

In [ ]:
# ============================================================
# CELL 22 — VERIFY PHRASEBANK
# ============================================================

print("=" * 60)
print("FINANCIALPHRASEBANK VERIFICATION")
print("=" * 60)

print("Shape:", phrasebank_normalized.shape)

print("\nColumns:")
print(phrasebank_normalized.columns.tolist())

print("\nLabel distribution:")
print(
    phrasebank_normalized["label"]
    .value_counts()
    .sort_index()
)

print("\nMissing values:")
print(
    phrasebank_normalized.isnull().sum()
)

print("\nDuplicate texts:")
print(
    phrasebank_normalized["text"].duplicated().sum()
)

print("\nSamples:")
display(
    phrasebank_normalized.head(10)
)


# Save
phrasebank_normalized.to_csv(
    PROCESSED_DIR / "phrasebank.csv",
    index=False
)

print(
    "\n✓ Saved:",
    PROCESSED_DIR / "phrasebank.csv"
)

============================================================
FINANCIALPHRASEBANK VERIFICATION
============================================================
Shape: (2264, 3)

Columns:
['text', 'label', 'source']

Label distribution:
label
0     303
1    1391
2     570
Name: count, dtype: int64

Missing values:
text      0
label     0
source    0
dtype: int64

Duplicate texts:
5

Samples:

                                                text  label      source
0  According to Gran , the company has no plans t...      1  phrasebank
1  For the last quarter of 2010 , Componenta 's n...      2  phrasebank
2  In the third quarter of 2010 , net sales incre...      2  phrasebank
3  Operating profit rose to EUR 13.1 mn from EUR ...      2  phrasebank
4  Operating profit totalled EUR 21.1 mn , up fro...      2  phrasebank
5  Finnish Talentum reports its operating profit ...      2  phrasebank
6  Clothing retail chain Sepp+ñl+ñ 's sales incre...      2  phrasebank
7  Consolidated net sales increased 16 % to reach...      2  phrasebank
8  Foundries division reports its sales increased...      2  phrasebank
9  HELSINKI ( AFX ) - Shares closed higher , led ...      2  phrasebank

✓ Saved: /home/amankhanduja/NLP_Project/HACE/data/processed/phrasebank.csv

In [ ]:
# ============================================================
# CELL 23 — INSPECT KAGGLE FINANCE NEWS
# ============================================================

print("=" * 60)
print("KAGGLE FINANCE NEWS SENTIMENTS")
print("=" * 60)


finance_news_files = list(
    FINANCE_NEWS_DIR.glob("*.csv")
)

print("CSV files found:")

for file in finance_news_files:
    print(
        f"  {file.name} "
        f"({file.stat().st_size / (1024 * 1024):.2f} MB)"
    )


if not finance_news_files:

    raise FileNotFoundError(
        "No CSV files found in data/raw/finance_news/"
    )


# Load first CSV
finance_news_file = finance_news_files[0]

finance_news = pd.read_csv(
    finance_news_file
)


print("\nFile loaded:")
print(finance_news_file)

print("\nShape:")
print(finance_news.shape)

print("\nColumns:")
print(finance_news.columns.tolist())

print("\nData types:")
print(finance_news.dtypes)

print("\nFirst 10 rows:")
display(finance_news.head(10))

============================================================
KAGGLE FINANCE NEWS SENTIMENTS
============================================================
CSV files found:
  dataset.csv (3.28 MB)

File loaded:
/home/amankhanduja/NLP_Project/HACE/data/raw/finance_news/dataset.csv

Shape:
(32583, 2)

Columns:
['sentiment', 'text']

Data types:
sentiment    object
text         object
dtype: object

First 10 rows:

  sentiment                                               text
0  positive  All banks, lending institutions may allow a th...
1   neutral                              Not so fast, Drake...
2  positive  FNF - ong  19.43. Trailing Stop  21.04 from 6 ...
3  positive  Dow opens down almost 500 points after China h...
4  positive  U.S. weekly active oil-rig count edges up by 1...
5   neutral         Grom Social Enterprises reports Q3 results
6  positive  Lumber Liquidators' stock rallies after CEO De...
7  positive  HG is breaking out ahead of an expected earnin...
8  positive  GAE Jumped over 1st Target and hit 2nd Target ...
9   neutral  Proline Plus is a mechanical liquid handling d...

In [ ]:
# ============================================================
# CELL 24 — NORMALIZE KAGGLE FINANCE NEWS
# ============================================================

print("=" * 60)
print("NORMALIZING FINANCE NEWS")
print("=" * 60)


# ------------------------------------------------------------
# Create normalized dataframe
# ------------------------------------------------------------

finance_news_normalized = finance_news[
    ["text", "sentiment"]
].copy()


# Rename sentiment → label
finance_news_normalized = (
    finance_news_normalized
    .rename(
        columns={
            "sentiment": "label"
        }
    )
)


# Add source
finance_news_normalized["source"] = (
    "finance_news"
)


# ------------------------------------------------------------
# Clean text
# ------------------------------------------------------------

# Convert to string
finance_news_normalized["text"] = (
    finance_news_normalized["text"]
    .astype("string")
    .str.strip()
)


# Remove missing / empty text
finance_news_normalized = (
    finance_news_normalized[
        finance_news_normalized["text"].notna()
    ]
    .copy()
)

finance_news_normalized = (
    finance_news_normalized[
        finance_news_normalized["text"] != ""
    ]
    .copy()
)


# ------------------------------------------------------------
# Convert labels
# ------------------------------------------------------------

finance_news_normalized["label"] = (
    finance_news_normalized["label"]
    .astype(str)
    .str.lower()
    .str.strip()
    .map({
        "negative": 0,
        "neutral": 1,
        "positive": 2
    })
)


# ------------------------------------------------------------
# Verify label conversion
# ------------------------------------------------------------

print("\nLabel distribution:")

print(
    finance_news_normalized["label"]
    .value_counts(dropna=False)
    .sort_index()
)


# Check invalid labels
invalid_labels = (
    finance_news_normalized["label"]
    .isna()
    .sum()
)

print(
    "\nInvalid / unmapped labels:",
    invalid_labels
)


if invalid_labels > 0:

    raise ValueError(
        "Some Finance News labels could not "
        "be mapped to 0/1/2."
    )


finance_news_normalized["label"] = (
    finance_news_normalized["label"]
    .astype(int)
)


# ------------------------------------------------------------
# Final schema
# ------------------------------------------------------------

finance_news_normalized = (
    finance_news_normalized[
        ["text", "label", "source"]
    ]
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# Final verification
# ------------------------------------------------------------

print("\nFinal shape:")
print(finance_news_normalized.shape)

print("\nColumns:")
print(finance_news_normalized.columns.tolist())

print("\nMissing values:")
print(finance_news_normalized.isnull().sum())

print("\nSamples:")
display(
    finance_news_normalized.head(10)
)

============================================================
NORMALIZING FINANCE NEWS
============================================================

Label distribution:
label
0    10852
1    10857
2    10860
Name: count, dtype: int64

Invalid / unmapped labels: 0

Final shape:
(32569, 3)

Columns:
['text', 'label', 'source']

Missing values:
text      0
label     0
source    0
dtype: int64

Samples:

                                                text  label        source
0  All banks, lending institutions may allow a th...      2  finance_news
1                              Not so fast, Drake...      1  finance_news
2  FNF - ong  19.43. Trailing Stop  21.04 from 6 ...      2  finance_news
3  Dow opens down almost 500 points after China h...      2  finance_news
4  U.S. weekly active oil-rig count edges up by 1...      2  finance_news
5         Grom Social Enterprises reports Q3 results      1  finance_news
6  Lumber Liquidators' stock rallies after CEO De...      2  finance_news
7  HG is breaking out ahead of an expected earnin...      2  finance_news
8  GAE Jumped over 1st Target and hit 2nd Target ...      2  finance_news
9  Proline Plus is a mechanical liquid handling d...      1  finance_news

In [ ]:
# ============================================================
# CELL 25 — SAVE FINANCE NEWS
# ============================================================

finance_news_normalized.to_csv(
    PROCESSED_DIR / "finance_news.csv",
    index=False
)

print(
    "✓ Saved:",
    PROCESSED_DIR / "finance_news.csv"
)

print(
    "Rows:",
    len(finance_news_normalized)
)

print(
    "Size:",
    finance_news_normalized.shape
)

✓ Saved: /home/amankhanduja/NLP_Project/HACE/data/processed/finance_news.csv
Rows: 32569
Size: (32569, 3)

In [ ]:
# ============================================================
# CELL 26 — FINAL DATASET SUMMARY
# ============================================================

normalized_datasets = {

    "FiQA Train":
        fiqa_train_normalized,

    "FiQA Validation":
        fiqa_valid_normalized,

    "FiQA Test":
        fiqa_test_normalized,

    "Twitter Train":
        twitter_train_normalized,

    "Twitter Validation":
        twitter_valid_normalized,

    "FinancialPhraseBank":
        phrasebank_normalized,

    "Finance News":
        finance_news_normalized
}


summary = []


for name, df in normalized_datasets.items():

    summary.append({

        "dataset": name,

        "rows": len(df),

        "columns": len(df.columns),

        "negative": (
            df["label"] == 0
        ).sum(),

        "neutral": (
            df["label"] == 1
        ).sum(),

        "positive": (
            df["label"] == 2
        ).sum(),

        "missing_text": (
            df["text"].isna()
        ).sum(),

        "duplicate_text": (
            df["text"].duplicated()
        ).sum()
    })


dataset_summary = pd.DataFrame(
    summary
)


display(dataset_summary)

,dataset,rows,columns,negative,neutral,positive,missing_text,duplicate_text
0,FiQA Train,822,3,237,72,513,0,52
1,FiQA Validation,117,3,42,9,66,0,6
2,FiQA Test,234,3,84,12,138,0,4
3,Twitter Train,9543,3,1442,1923,6178,0,3
4,Twitter Validation,2388,3,347,475,1566,0,0
5,FinancialPhraseBank,2264,3,303,1391,570,0,5
6,Finance News,32569,3,10852,10857,10860,0,159

In [ ]:
# ============================================================
# CELL 30 — DUPLICATE / LEAKAGE AUDIT
# ============================================================

print("=" * 60)
print("DUPLICATE / LEAKAGE AUDIT")
print("=" * 60)


def normalize_for_duplicate_check(text):
    return (
        str(text)
        .lower()
        .strip()
    )


# ------------------------------------------------------------
# Create datasets to audit
# ------------------------------------------------------------

audit_datasets = {
    "fiqa_train": fiqa_train_normalized,
    "fiqa_validation": fiqa_valid_normalized,
    "fiqa_test": fiqa_test_normalized,

    "twitter_train": twitter_train_normalized,
    "twitter_validation": twitter_valid_normalized,

    "phrasebank": phrasebank_normalized,

    "finance_news": finance_news_normalized
}


# ------------------------------------------------------------
# Normalize text for comparison
# ------------------------------------------------------------

for name, df in audit_datasets.items():

    df["_duplicate_key"] = (
        df["text"]
        .apply(normalize_for_duplicate_check)
    )


# ------------------------------------------------------------
# Function to find overlap
# ------------------------------------------------------------

def find_overlap(df1, df2):

    keys1 = set(df1["_duplicate_key"])
    keys2 = set(df2["_duplicate_key"])

    return keys1.intersection(keys2)


# ------------------------------------------------------------
# Important split comparisons
# ------------------------------------------------------------

comparisons = [
    ("fiqa_train", "fiqa_validation"),
    ("fiqa_train", "fiqa_test"),
    ("fiqa_validation", "fiqa_test"),

    ("twitter_train", "twitter_validation")
]


print("\nSplit leakage checks:\n")


for name1, name2 in comparisons:

    overlap = find_overlap(
        audit_datasets[name1],
        audit_datasets[name2]
    )

    print(
        f"{name1:20} ↔ {name2:20} : "
        f"{len(overlap)} duplicates"
    )

============================================================
DUPLICATE / LEAKAGE AUDIT
============================================================

Split leakage checks:

fiqa_train           ↔ fiqa_validation      : 0 duplicates
fiqa_train           ↔ fiqa_test            : 0 duplicates
fiqa_validation      ↔ fiqa_test            : 0 duplicates
twitter_train        ↔ twitter_validation   : 0 duplicates

In [ ]:
# ============================================================
# CELL 31 — CROSS-DATASET OVERLAP
# ============================================================

print("=" * 60)
print("CROSS-DATASET OVERLAP")
print("=" * 60)


dataset_names = list(
    audit_datasets.keys()
)


cross_source_results = []


for i in range(
    len(dataset_names)
):

    for j in range(
        i + 1,
        len(dataset_names)
    ):

        name1 = dataset_names[i]
        name2 = dataset_names[j]

        overlap = find_overlap(
            audit_datasets[name1],
            audit_datasets[name2]
        )

        cross_source_results.append({

            "dataset_1": name1,

            "dataset_2": name2,

            "overlap_count": len(overlap)
        })


cross_source_df = pd.DataFrame(
    cross_source_results
)


display(
    cross_source_df.sort_values(
        "overlap_count",
        ascending=False
    )
)

============================================================
CROSS-DATASET OVERLAP
============================================================

             dataset_1           dataset_2  overlap_count
17       twitter_train        finance_news           4849
20          phrasebank        finance_news           2170
19  twitter_validation        finance_news           1208
11           fiqa_test       twitter_train              0
18  twitter_validation          phrasebank              0
16       twitter_train          phrasebank              0
15       twitter_train  twitter_validation              0
14           fiqa_test        finance_news              0
13           fiqa_test          phrasebank              0
12           fiqa_test  twitter_validation              0
0           fiqa_train     fiqa_validation              0
1           fiqa_train           fiqa_test              0
9      fiqa_validation          phrasebank              0
8      fiqa_validation  twitter_validation              0
7      fiqa_validation       twitter_train              0
6      fiqa_validation           fiqa_test              0
5           fiqa_train        finance_news              0
4           fiqa_train          phrasebank              0
3           fiqa_train  twitter_validation              0
2           fiqa_train       twitter_train              0
10     fiqa_validation        finance_news              0

In [ ]:
# ============================================================
# CELL 32 — REMOVE INTERNAL DUPLICATES
# ============================================================

print("=" * 60)
print("INTERNAL DUPLICATE REMOVAL")
print("=" * 60)


def remove_internal_duplicates(
    df,
    dataset_name
):

    before = len(df)

    result = (
        df
        .drop_duplicates(
            subset=["text"]
        )
        .reset_index(drop=True)
    )

    after = len(result)

    print(
        f"{dataset_name:20} "
        f"{before:8} → {after:8} "
        f"removed: {before - after}"
    )

    return result


fiqa_train_normalized = remove_internal_duplicates(
    fiqa_train_normalized,
    "FiQA Train"
)

fiqa_valid_normalized = remove_internal_duplicates(
    fiqa_valid_normalized,
    "FiQA Validation"
)

fiqa_test_normalized = remove_internal_duplicates(
    fiqa_test_normalized,
    "FiQA Test"
)

twitter_train_normalized = remove_internal_duplicates(
    twitter_train_normalized,
    "Twitter Train"
)

twitter_valid_normalized = remove_internal_duplicates(
    twitter_valid_normalized,
    "Twitter Validation"
)

phrasebank_normalized = remove_internal_duplicates(
    phrasebank_normalized,
    "PhraseBank"
)

finance_news_normalized = remove_internal_duplicates(
    finance_news_normalized,
    "Finance News"
)

============================================================
INTERNAL DUPLICATE REMOVAL
============================================================
FiQA Train                822 →      770 removed: 52
FiQA Validation           117 →      111 removed: 6
FiQA Test                 234 →      230 removed: 4
Twitter Train            9543 →     9540 removed: 3
Twitter Validation       2388 →     2388 removed: 0
PhraseBank               2264 →     2259 removed: 5
Finance News            32569 →    32410 removed: 159

In [ ]:
# ============================================================
# CELL 33 — CREATE CONTROLLED SPLITS
# ============================================================

from sklearn.model_selection import train_test_split


RANDOM_SEED = 42


def create_stratified_splits(
    df,
    dataset_name
):

    # --------------------------------------------------------
    # First: 80% train / 20% temporary
    # --------------------------------------------------------

    train_df, temp_df = train_test_split(
        df,
        test_size=0.20,
        random_state=RANDOM_SEED,
        stratify=df["label"]
    )


    # --------------------------------------------------------
    # Second: temporary → 10% validation / 10% test
    # --------------------------------------------------------

    validation_df, test_df = train_test_split(
        temp_df,
        test_size=0.50,
        random_state=RANDOM_SEED,
        stratify=temp_df["label"]
    )


    # Reset indices
    train_df = train_df.reset_index(drop=True)
    validation_df = validation_df.reset_index(drop=True)
    test_df = test_df.reset_index(drop=True)


    print(
        f"\n{dataset_name}"
    )

    print(
        f"Train      : {len(train_df)}"
    )

    print(
        f"Validation : {len(validation_df)}"
    )

    print(
        f"Test       : {len(test_df)}"
    )


    return (
        train_df,
        validation_df,
        test_df
    )


# ------------------------------------------------------------
# PhraseBank
# ------------------------------------------------------------

phrasebank_train, \
phrasebank_validation, \
phrasebank_test = create_stratified_splits(
    phrasebank_normalized,
    "FinancialPhraseBank"
)


# ------------------------------------------------------------
# Finance News
# ------------------------------------------------------------

finance_news_train, \
finance_news_validation, \
finance_news_test = create_stratified_splits(
    finance_news_normalized,
    "Finance News"
)

FinancialPhraseBank
Train      : 1807
Validation : 226
Test       : 226

Finance News
Train      : 25928
Validation : 3241
Test       : 3241

In [ ]:
# ============================================================
# CELL 34 — FINAL SPLIT DISTRIBUTION
# ============================================================

print("=" * 60)
print("FINAL CLASS DISTRIBUTIONS")
print("=" * 60)


final_splits = {

    "FiQA Train":
        fiqa_train_normalized,

    "FiQA Validation":
        fiqa_valid_normalized,

    "FiQA Test":
        fiqa_test_normalized,

    "Twitter Train":
        twitter_train_normalized,

    "Twitter Validation":
        twitter_valid_normalized,

    "PhraseBank Train":
        phrasebank_train,

    "PhraseBank Validation":
        phrasebank_validation,

    "PhraseBank Test":
        phrasebank_test,

    "Finance News Train":
        finance_news_train,

    "Finance News Validation":
        finance_news_validation,

    "Finance News Test":
        finance_news_test
}


distribution_rows = []


for name, df in final_splits.items():

    distribution_rows.append({

        "split": name,

        "rows": len(df),

        "negative": (
            df["label"] == 0
        ).sum(),

        "neutral": (
            df["label"] == 1
        ).sum(),

        "positive": (
            df["label"] == 2
        ).sum()
    })


final_distribution = pd.DataFrame(
    distribution_rows
)


display(
    final_distribution
)

============================================================
FINAL CLASS DISTRIBUTIONS
============================================================

                      split   rows  negative  neutral  positive
0                FiQA Train    770       224       64       482
1           FiQA Validation    111        39        9        63
2                 FiQA Test    230        83       12       135
3             Twitter Train   9540      1442     1922      6176
4        Twitter Validation   2388       347      475      1566
5          PhraseBank Train   1807       242     1109       456
6     PhraseBank Validation    226        30      139        57
7           PhraseBank Test    226        31      138        57
8        Finance News Train  25928      8657     8600      8671
9   Finance News Validation   3241      1082     1075      1084
10        Finance News Test   3241      1082     1075      1084

In [ ]:
# ============================================================
# CELL 35 — SAVE FINAL EXPERIMENTAL DATASETS
# ============================================================

FINAL_DIR = PROCESSED_DIR / "final"

FINAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


final_files = {

    "fiqa_train.csv":
        fiqa_train_normalized,

    "fiqa_validation.csv":
        fiqa_valid_normalized,

    "fiqa_test.csv":
        fiqa_test_normalized,

    "twitter_train.csv":
        twitter_train_normalized,

    "twitter_validation.csv":
        twitter_valid_normalized,

    "phrasebank_train.csv":
        phrasebank_train,

    "phrasebank_validation.csv":
        phrasebank_validation,

    "phrasebank_test.csv":
        phrasebank_test,

    "finance_news_train.csv":
        finance_news_train,

    "finance_news_validation.csv":
        finance_news_validation,

    "finance_news_test.csv":
        finance_news_test
}


# Remove the temporary column created by the duplicate audit before export.
for df in final_files.values():
    if "_duplicate_key" in df.columns:
        df.drop(columns=["_duplicate_key"], inplace=True)

for filename, df in final_files.items():

    path = FINAL_DIR / filename

    df.to_csv(
        path,
        index=False
    )

    print(
        f"✓ {filename:35} "
        f"{df.shape}"
    )


# Save distribution report

final_distribution.to_csv(
    FINAL_DIR / "class_distribution.csv",
    index=False
)


print("\n" + "=" * 60)
print("FINAL DATA PREPARATION COMPLETE")
print("=" * 60)

print(
    "\nFinal directory:"
)

print(
    FINAL_DIR
)

✓ fiqa_train.csv                      (770, 3)
✓ fiqa_validation.csv                 (111, 3)
✓ fiqa_test.csv                       (230, 3)
✓ twitter_train.csv                   (9540, 3)
✓ twitter_validation.csv              (2388, 3)
✓ phrasebank_train.csv                (1807, 3)
✓ phrasebank_validation.csv           (226, 3)
✓ phrasebank_test.csv                 (226, 3)
✓ finance_news_train.csv              (25928, 3)
✓ finance_news_validation.csv         (3241, 3)
✓ finance_news_test.csv               (3241, 3)

============================================================
FINAL DATA PREPARATION COMPLETE
============================================================

Final directory:
/home/amankhanduja/NLP_Project/HACE/data/processed/final

In [ ]:
# ============================================================
# CELL 36 — FINAL INTEGRITY CHECK
# ============================================================

print("=" * 60)
print("FINAL DATA INTEGRITY CHECK")
print("=" * 60)


errors = []


for filename, df in final_files.items():

    # Required columns
    expected_columns = [
        "text",
        "label",
        "source"
    ]

    if list(df.columns) != expected_columns:

        errors.append(
            f"{filename}: incorrect columns"
        )


    # Missing text
    if df["text"].isna().any():

        errors.append(
            f"{filename}: missing text"
        )


    # Missing labels
    if df["label"].isna().any():

        errors.append(
            f"{filename}: missing labels"
        )


    # Valid labels
    invalid_labels = (
        ~df["label"].isin([0, 1, 2])
    ).sum()

    if invalid_labels > 0:

        errors.append(
            f"{filename}: "
            f"{invalid_labels} invalid labels"
        )


    # Empty text
    empty_text = (
        df["text"]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    if empty_text > 0:

        errors.append(
            f"{filename}: "
            f"{empty_text} empty texts"
        )


# ------------------------------------------------------------
# Report
# ------------------------------------------------------------

if errors:

    print("\n❌ DATA PREPARATION HAS ERRORS:\n")

    for error in errors:
        print(" -", error)

    raise ValueError(
        "Fix data integrity issues before training."
    )


else:

    print(
        "\n✓ No integrity errors found."
    )

    print(
        "✓ All datasets use:"
    )

    print(
        "  text | label | source"
    )

    print(
        "✓ Labels are 0 / 1 / 2"
    )

    print(
        "✓ No missing text"
    )

    print(
        "✓ No missing labels"
    )

    print(
        "✓ Final splits saved"
    )

    print(
        "\nDATA PREPARATION = COMPLETE"
    )

============================================================
FINAL DATA INTEGRITY CHECK
============================================================

✓ No integrity errors found.
✓ All datasets use:
  text | label | source
✓ Labels are 0 / 1 / 2
✓ No missing text
✓ No missing labels
✓ Final splits saved

DATA PREPARATION = COMPLETE

In [ ]:
# ============================================================
# FIX — REMOVE TEMPORARY AUDIT COLUMN
# ============================================================

ALL_DATAFRAMES = [
    fiqa_train_normalized,
    fiqa_valid_normalized,
    fiqa_test_normalized,
    twitter_train_normalized,
    twitter_valid_normalized,
    phrasebank_normalized,
    finance_news_normalized,
    phrasebank_train,
    phrasebank_validation,
    phrasebank_test,
    finance_news_train,
    finance_news_validation,
    finance_news_test
]

for df in ALL_DATAFRAMES:

    if "_duplicate_key" in df.columns:
        df.drop(
            columns=["_duplicate_key"],
            inplace=True
        )

print("✓ Temporary duplicate-audit column removed")

print("\nChecking columns:")

for name, df in [
    ("FiQA Train", fiqa_train_normalized),
    ("FiQA Validation", fiqa_valid_normalized),
    ("FiQA Test", fiqa_test_normalized),
    ("Twitter Train", twitter_train_normalized),
    ("Twitter Validation", twitter_valid_normalized),
    ("PhraseBank Train", phrasebank_train),
    ("PhraseBank Validation", phrasebank_validation),
    ("PhraseBank Test", phrasebank_test),
    ("Finance News Train", finance_news_train),
    ("Finance News Validation", finance_news_validation),
    ("Finance News Test", finance_news_test),
]:

    print(
        f"{name:30} → {list(df.columns)}"
    )

✓ Temporary duplicate-audit column removed

Checking columns:
FiQA Train                     → ['text', 'label', 'source']
FiQA Validation                → ['text', 'label', 'source']
FiQA Test                      → ['text', 'label', 'source']
Twitter Train                  → ['text', 'label', 'source']
Twitter Validation             → ['text', 'label', 'source']
PhraseBank Train               → ['text', 'label', 'source']
PhraseBank Validation          → ['text', 'label', 'source']
PhraseBank Test                → ['text', 'label', 'source']
Finance News Train             → ['text', 'label', 'source']
Finance News Validation        → ['text', 'label', 'source']
Finance News Test              → ['text', 'label', 'source']