In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent

FINAL_DATA_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "final"
)

print("Project:", PROJECT_ROOT)
print("Data:", FINAL_DATA_DIR)

for file in sorted(FINAL_DATA_DIR.glob("*.csv")):
    print(file.name)

Project: /
Data: /data/processed/final

In [2]:
!git clone https://github.com/Sealie145/HACE_Financial_Sentiment_Analysis.git /content/HACE_Financial_Sentiment_Analysis

Cloning into '/content/HACE_Financial_Sentiment_Analysis'...
remote: Enumerating objects: 123, done.
remote: Counting objects: 100% (123/123), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 123 (delta 31), reused 110 (delta 18), pack-reused 0 (from 0)
Receiving objects: 100% (123/123), 2.09 MiB | 5.32 MiB/s, done.
Resolving deltas: 100% (31/31), done.

In [4]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/HACE_Financial_Sentiment_Analysis"
)

FINAL_DATA_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "final"
)

print("Project:", PROJECT_ROOT)
print("Final data:", FINAL_DATA_DIR)
print("Exists:", FINAL_DATA_DIR.exists())

print("\nCSV files:")
for file in sorted(FINAL_DATA_DIR.glob("*.csv")):
    print("✓", file.name)

Project: /content/HACE_Financial_Sentiment_Analysis
Final data: /content/HACE_Financial_Sentiment_Analysis/data/processed/final
Exists: True

CSV files:
✓ class_distribution.csv
✓ finance_news_test.csv
✓ finance_news_train.csv
✓ finance_news_validation.csv
✓ fiqa_test.csv
✓ fiqa_train.csv
✓ fiqa_validation.csv
✓ phrasebank_test.csv
✓ phrasebank_train.csv
✓ phrasebank_validation.csv
✓ twitter_train.csv
✓ twitter_validation.csv

In [3]:
%cd /content/HACE_Financial_Sentiment_Analysis

/content/HACE_Financial_Sentiment_Analysis

In [18]:
!git pull origin main

remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 3), reused 17 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (17/17), 1.81 MiB | 3.20 MiB/s, done.
From https://github.com/Sealie145/HACE_Financial_Sentiment_Analysis
 * branch            main       -> FETCH_HEAD
   920a80c..40414b7  main       -> origin/main
Updating 920a80c..40414b7
Fast-forward
 data/processed/final/class_distribution.csv      |    12 +
 data/processed/final/finance_news_test.csv       |  3242 +++
 data/processed/final/finance_news_train.csv      | 25929 +++++++++++++++++++++
 data/processed/final/finance_news_validation.csv |  3242 +++
 data/processed/final/fiqa_test.csv               |   231 +
 data/processed/final/fiqa_train.csv              |   771 +
 data/processed/final/fiqa_validation.csv         |   112 +
 data/processed/final/phrasebank_test.csv         |   227 +
 data/processed/final/phrasebank_train.csv        |  1808 ++
 data/processed/final/phrasebank_validation.csv   |   227 +
 data/processed/final/twitter_train.csv           |  9936 ++++++++
 data/processed/final/twitter_validation.csv      |  2487 ++
 12 files changed, 48224 insertions(+)
 create mode 100644 data/processed/final/class_distribution.csv
 create mode 100644 data/processed/final/finance_news_test.csv
 create mode 100644 data/processed/final/finance_news_train.csv
 create mode 100644 data/processed/final/finance_news_validation.csv
 create mode 100644 data/processed/final/fiqa_test.csv
 create mode 100644 data/processed/final/fiqa_train.csv
 create mode 100644 data/processed/final/fiqa_validation.csv
 create mode 100644 data/processed/final/phrasebank_test.csv
 create mode 100644 data/processed/final/phrasebank_train.csv
 create mode 100644 data/processed/final/phrasebank_validation.csv
 create mode 100644 data/processed/final/twitter_train.csv
 create mode 100644 data/processed/final/twitter_validation.csv

In [5]:
import pandas as pd

def load_split(filename):
    path = FINAL_DATA_DIR / filename

    if not path.exists():
        raise FileNotFoundError(f"Missing: {path}")

    df = pd.read_csv(path)

    print(f"{filename:35} {df.shape}")

    return df


# FiQA
fiqa_train = load_split("fiqa_train.csv")
fiqa_val   = load_split("fiqa_validation.csv")
fiqa_test  = load_split("fiqa_test.csv")

# Twitter
twitter_train = load_split("twitter_train.csv")
twitter_val   = load_split("twitter_validation.csv")

# PhraseBank
phrasebank_train = load_split("phrasebank_train.csv")
phrasebank_val   = load_split("phrasebank_validation.csv")
phrasebank_test  = load_split("phrasebank_test.csv")

# Finance News
finance_news_train = load_split("finance_news_train.csv")
finance_news_val   = load_split("finance_news_validation.csv")
finance_news_test  = load_split("finance_news_test.csv")

print("\n✓ All datasets loaded.")

fiqa_train.csv                      (770, 3)
fiqa_validation.csv                 (111, 3)
fiqa_test.csv                       (230, 3)
twitter_train.csv                   (9540, 3)
twitter_validation.csv              (2388, 3)
phrasebank_train.csv                (1807, 3)
phrasebank_validation.csv           (226, 3)
phrasebank_test.csv                 (226, 3)
finance_news_train.csv              (25928, 3)
finance_news_validation.csv         (3241, 3)
finance_news_test.csv               (3241, 3)

✓ All datasets loaded.

In [6]:
datasets_to_check = {
    "FiQA": fiqa_train,
    "Twitter": twitter_train,
    "PhraseBank": phrasebank_train,
    "Finance News": finance_news_train,
}

for name, df in datasets_to_check.items():

    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    print("Shape:", df.shape)
    print("Columns:", list(df.columns))

    print("\nLabel distribution:")
    print(df["label"].value_counts().sort_index())

    print("\nMissing values:")
    print(df[["text", "label"]].isna().sum())

============================================================
FiQA
============================================================
Shape: (770, 3)
Columns: ['text', 'label', 'source']

Label distribution:
label
0    224
1     64
2    482
Name: count, dtype: int64

Missing values:
text     0
label    0
dtype: int64

============================================================
Twitter
============================================================
Shape: (9540, 3)
Columns: ['text', 'label', 'source']

Label distribution:
label
0    1442
1    1922
2    6176
Name: count, dtype: int64

Missing values:
text     0
label    0
dtype: int64

============================================================
PhraseBank
============================================================
Shape: (1807, 3)
Columns: ['text', 'label', 'source']

Label distribution:
label
0     242
1    1109
2     456
Name: count, dtype: int64

Missing values:
text     0
label    0
dtype: int64

============================================================
Finance News
============================================================
Shape: (25928, 3)
Columns: ['text', 'label', 'source']

Label distribution:
label
0    8657
1    8600
2    8671
Name: count, dtype: int64

Missing values:
text     0
label    0
dtype: int64

In [8]:
# ============================================================
# CELL 9 — LOAD FINBERT
# ============================================================

import torch
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification
)

MODEL_NAME = "ProsusAI/finbert"

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", DEVICE)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))


tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=3,
    ignore_mismatched_sizes=True
)

model.to(DEVICE)

print("\n✓ FinBERT loaded")
print("Parameters:", sum(p.numel() for p in model.parameters()))

Device: cuda
GPU: Tesla T4

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  438MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

✓ FinBERT loaded
Parameters: 109484547

In [9]:
# ============================================================
# CELL 11 — TRAINING CONFIGURATION
# ============================================================

SEED = 42

MAX_LENGTH = 128
BATCH_SIZE = 16
LEARNING_RATE = 2e-5
EPOCHS = 3
WEIGHT_DECAY = 0.01
WARMUP_RATIO = 0.1

MODEL_DIR = (
    PROJECT_ROOT
    / "models"
)

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("Training configuration")
print("-" * 40)
print("Model:", MODEL_NAME)
print("Max length:", MAX_LENGTH)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Epochs:", EPOCHS)
print("Weight decay:", WEIGHT_DECAY)
print("Device:", DEVICE)

Training configuration
----------------------------------------
Model: ProsusAI/finbert
Max length: 128
Batch size: 16
Learning rate: 2e-05
Epochs: 3
Weight decay: 0.01
Device: cuda

In [10]:
# ============================================================
# CELL 12 — TOKENIZATION PIPELINE
# ============================================================

from torch.utils.data import Dataset, DataLoader


class FinancialDataset(Dataset):

    def __init__(self, dataframe, tokenizer, max_length=128):
        self.texts = dataframe["text"].astype(str).tolist()
        self.labels = dataframe["label"].astype(int).tolist()
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):

        encoding = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt"
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels": torch.tensor(
                self.labels[idx],
                dtype=torch.long
            )
        }


# ------------------------------------------------------------
# Create FiQA datasets
# ------------------------------------------------------------

fiqa_train_dataset = FinancialDataset(
    fiqa_train,
    tokenizer,
    MAX_LENGTH
)

fiqa_val_dataset = FinancialDataset(
    fiqa_val,
    tokenizer,
    MAX_LENGTH
)

fiqa_test_dataset = FinancialDataset(
    fiqa_test,
    tokenizer,
    MAX_LENGTH
)

print("FiQA datasets created")

print("Train:", len(fiqa_train_dataset))
print("Validation:", len(fiqa_val_dataset))
print("Test:", len(fiqa_test_dataset))

FiQA datasets created
Train: 770
Validation: 111
Test: 230

In [27]:
# ============================================================
# CELL 13 — DATALOADERS
# ============================================================

fiqa_train_loader = DataLoader(
    fiqa_train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

fiqa_val_loader = DataLoader(
    fiqa_val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

fiqa_test_loader = DataLoader(
    fiqa_test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print("Train batches:", len(fiqa_train_loader))
print("Validation batches:", len(fiqa_val_loader))
print("Test batches:", len(fiqa_test_loader))

Train batches: 49
Validation batches: 7
Test batches: 15

In [12]:
# ============================================================
# CELL 14 — GPU BATCH TEST
# ============================================================

batch = next(iter(fiqa_train_loader))

input_ids = batch["input_ids"].to(DEVICE)
attention_mask = batch["attention_mask"].to(DEVICE)
labels = batch["labels"].to(DEVICE)

print("Input shape:", input_ids.shape)
print("Attention mask:", attention_mask.shape)
print("Labels:", labels.shape)

with torch.no_grad():

    outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask
    )

print("Logits shape:", outputs.logits.shape)
print("Logits device:", outputs.logits.device)

print("\n✓ Forward pass successful")

NameError: name 'fiqa_train_loader' is not defined

In [11]:
# ============================================================
# CELL 15 — TRAINING UTILITIES
# ============================================================

import copy
import time
import numpy as np

from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix
)

from torch.optim import AdamW
from tqdm.auto import tqdm


def evaluate_model(model, dataloader, device):
    """
    Evaluate model on validation/test data.
    """

    model.eval()

    all_predictions = []
    all_labels = []

    total_loss = 0.0
    total_samples = 0

    criterion = torch.nn.CrossEntropyLoss()

    with torch.no_grad():

        for batch in tqdm(
            dataloader,
            desc="Evaluating",
            leave=False
        ):

            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )

            loss = outputs.loss

            predictions = torch.argmax(
                outputs.logits,
                dim=1
            )

            batch_size = labels.size(0)

            total_loss += (
                loss.item() * batch_size
            )

            total_samples += batch_size

            all_predictions.extend(
                predictions.cpu().numpy()
            )

            all_labels.extend(
                labels.cpu().numpy()
            )

    avg_loss = total_loss / total_samples

    accuracy = accuracy_score(
        all_labels,
        all_predictions
    )

    precision, recall, f1, _ = (
        precision_recall_fscore_support(
            all_labels,
            all_predictions,
            average="macro",
            zero_division=0
        )
    )

    return {
        "loss": avg_loss,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "predictions": np.array(all_predictions),
        "labels": np.array(all_labels)
    }


def train_model(
    model,
    train_loader,
    val_loader,
    device,
    epochs=3,
    learning_rate=2e-5,
    weight_decay=0.01,
    save_path=None,
    patience=2
):

    optimizer = AdamW(
        model.parameters(),
        lr=learning_rate,
        weight_decay=weight_decay
    )

    best_f1 = -1.0
    best_state = None
    patience_counter = 0

    history = []

    print("=" * 60)
    print("TRAINING")
    print("=" * 60)

    for epoch in range(epochs):

        print(
            f"\nEpoch {epoch + 1}/{epochs}"
        )

        start_time = time.time()

        # ----------------------------------------------------
        # Training
        # ----------------------------------------------------

        model.train()

        total_train_loss = 0.0
        total_train_samples = 0

        progress_bar = tqdm(
            train_loader,
            desc="Training"
        )

        for batch in progress_bar:

            input_ids = batch["input_ids"].to(
                device,
                non_blocking=True
            )

            attention_mask = batch[
                "attention_mask"
            ].to(
                device,
                non_blocking=True
            )

            labels = batch["labels"].to(
                device,
                non_blocking=True
            )

            optimizer.zero_grad(
                set_to_none=True
            )

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )

            loss = outputs.loss

            loss.backward()

            optimizer.step()

            batch_size = labels.size(0)

            total_train_loss += (
                loss.item() * batch_size
            )

            total_train_samples += batch_size

            progress_bar.set_postfix(
                loss=f"{loss.item():.4f}"
            )

        train_loss = (
            total_train_loss
            / total_train_samples
        )

        # ----------------------------------------------------
        # Validation
        # ----------------------------------------------------

        val_metrics = evaluate_model(
            model,
            val_loader,
            device
        )

        epoch_time = (
            time.time() - start_time
        )

        print(
            f"\nTrain Loss : {train_loss:.4f}"
        )

        print(
            f"Val Loss   : {val_metrics['loss']:.4f}"
        )

        print(
            f"Val Acc    : {val_metrics['accuracy']:.4f}"
        )

        print(
            f"Val F1     : {val_metrics['f1']:.4f}"
        )

        print(
            f"Time       : {epoch_time:.1f}s"
        )

        history.append({
            "epoch": epoch + 1,
            "train_loss": train_loss,
            "val_loss": val_metrics["loss"],
            "val_accuracy": val_metrics["accuracy"],
            "val_precision": val_metrics["precision"],
            "val_recall": val_metrics["recall"],
            "val_f1": val_metrics["f1"],
            "time_seconds": epoch_time
        })

        # ----------------------------------------------------
        # Best model checkpoint
        # ----------------------------------------------------

        if val_metrics["f1"] > best_f1:

            best_f1 = val_metrics["f1"]

            best_state = copy.deepcopy(
                model.state_dict()
            )

            patience_counter = 0

            print(
                f"✓ New best model "
                f"(F1 = {best_f1:.4f})"
            )

            if save_path is not None:

                torch.save(
                    {
                        "model_state_dict": best_state,
                        "best_val_f1": best_f1,
                        "epoch": epoch + 1
                    },
                    save_path
                )

                print(
                    f"✓ Checkpoint saved → "
                    f"{save_path}"
                )

        else:

            patience_counter += 1

            print(
                f"No improvement "
                f"({patience_counter}/{patience})"
            )

            if patience_counter >= patience:

                print(
                    "\nEarly stopping."
                )

                break

    # --------------------------------------------------------
    # Restore best model
    # --------------------------------------------------------

    if best_state is not None:

        model.load_state_dict(
            best_state
        )

    print("\n" + "=" * 60)
    print(
        f"BEST VALIDATION F1: {best_f1:.4f}"
    )
    print("=" * 60)

    return model, pd.DataFrame(history)

In [31]:
# ============================================================
# CELL 16 — TRAIN FiQA EXPERT
# ============================================================

fiqa_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=3,
    ignore_mismatched_sizes=True
)

fiqa_model.to(DEVICE)

fiqa_checkpoint = (
    MODEL_DIR / "fiqa_expert.pt"
)

fiqa_model, fiqa_history = train_model(
    model=fiqa_model,
    train_loader=fiqa_train_loader,
    val_loader=fiqa_val_loader,
    device=DEVICE,
    epochs=EPOCHS,
    learning_rate=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
    save_path=fiqa_checkpoint,
    patience=2
)

display(fiqa_history)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

============================================================
TRAINING
============================================================

Epoch 1/3

Training:   0%|          | 0/49 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/7 [00:00<?, ?it/s]

Train Loss : 0.9324
Val Loss   : 0.8232
Val Acc    : 0.5676
Val F1     : 0.2414
Time       : 18.3s
✓ New best model (F1 = 0.2414)
✓ Checkpoint saved → /content/HACE_Financial_Sentiment_Analysis/models/fiqa_expert.pt

Epoch 2/3

Training:   0%|          | 0/49 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/7 [00:00<?, ?it/s]

Train Loss : 0.7578
Val Loss   : 0.7538
Val Acc    : 0.7027
Val F1     : 0.6246
Time       : 17.9s
✓ New best model (F1 = 0.6246)
✓ Checkpoint saved → /content/HACE_Financial_Sentiment_Analysis/models/fiqa_expert.pt

Epoch 3/3

Training:   0%|          | 0/49 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/7 [00:00<?, ?it/s]

Train Loss : 0.5419
Val Loss   : 0.5478
Val Acc    : 0.8108
Val F1     : 0.7145
Time       : 18.6s
✓ New best model (F1 = 0.7145)
✓ Checkpoint saved → /content/HACE_Financial_Sentiment_Analysis/models/fiqa_expert.pt

============================================================
BEST VALIDATION F1: 0.7145
============================================================

,epoch,train_loss,val_loss,val_accuracy,val_precision,val_recall,val_f1,time_seconds
0,1,0.932351,0.823237,0.567568,0.189189,0.333333,0.241379,18.340904
1,2,0.757831,0.753775,0.702703,0.688074,0.617013,0.624572,17.866205
2,3,0.541947,0.547771,0.810811,0.745605,0.694343,0.714483,18.559338

In [32]:
# ============================================================
# CELL 17 — FiQA TEST EVALUATION
# ============================================================

fiqa_test_metrics = evaluate_model(
    fiqa_model,
    fiqa_test_loader,
    DEVICE
)

print("=" * 60)
print("FiQA TEST RESULTS")
print("=" * 60)

print(
    f"Accuracy : {fiqa_test_metrics['accuracy']:.4f}"
)

print(
    f"Precision: {fiqa_test_metrics['precision']:.4f}"
)

print(
    f"Recall   : {fiqa_test_metrics['recall']:.4f}"
)

print(
    f"F1       : {fiqa_test_metrics['f1']:.4f}"
)

print("\nClassification Report:\n")

print(
    classification_report(
        fiqa_test_metrics["labels"],
        fiqa_test_metrics["predictions"],
        target_names=[
            "Negative",
            "Neutral",
            "Positive"
        ],
        digits=4,
        zero_division=0
    )
)

Evaluating:   0%|          | 0/15 [00:00<?, ?it/s]

============================================================
FiQA TEST RESULTS
============================================================
Accuracy : 0.7478
Precision: 0.6318
Recall   : 0.5604
F1       : 0.5790

Classification Report:

              precision    recall  f1-score   support

    Negative     0.7237    0.6627    0.6918        83
     Neutral     0.4000    0.1667    0.2353        12
    Positive     0.7718    0.8519    0.8099       135

    accuracy                         0.7478       230
   macro avg     0.6318    0.5604    0.5790       230
weighted avg     0.7350    0.7478    0.7373       230

In [36]:
# ============================================================
# SAVE FIQA EXPERT TO GOOGLE DRIVE — ONE CELL
# ============================================================

from google.colab import drive
from pathlib import Path
import json

# ------------------------------------------------------------
# 1. Mount Google Drive
# ------------------------------------------------------------

drive.mount("/content/drive")

# ------------------------------------------------------------
# 2. Create FiQA model directory
# ------------------------------------------------------------

FIQA_DIR = Path(
    "/content/drive/MyDrive/HACE_models/fiqa"
)

FIQA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# 3. Save complete Hugging Face model
# ------------------------------------------------------------

fiqa_model.save_pretrained(
    FIQA_DIR,
    safe_serialization=True
)

# ------------------------------------------------------------
# 4. Save tokenizer
# ------------------------------------------------------------

tokenizer.save_pretrained(
    FIQA_DIR
)

# ------------------------------------------------------------
# 5. Save training history
# ------------------------------------------------------------

fiqa_history.to_csv(
    FIQA_DIR / "training_history.csv",
    index=False
)

# ------------------------------------------------------------
# 6. Save test metrics
# ------------------------------------------------------------

test_results = {
    "accuracy": float(fiqa_test_metrics["accuracy"]),
    "macro_precision": float(
        fiqa_test_metrics["precision"]
    ),
    "macro_recall": float(
        fiqa_test_metrics["recall"]
    ),
    "macro_f1": float(
        fiqa_test_metrics["f1"]
    )
}

with open(
    FIQA_DIR / "test_results.json",
    "w"
) as f:
    json.dump(
        test_results,
        f,
        indent=4
    )

# ------------------------------------------------------------
# 7. Verify everything
# ------------------------------------------------------------

print("=" * 60)
print("✓ FIQA EXPERT SAVED TO GOOGLE DRIVE")
print("=" * 60)

print(f"\nLocation:")
print(FIQA_DIR)

print("\nFiles:")

for file in sorted(FIQA_DIR.iterdir()):
    size_mb = file.stat().st_size / (1024 ** 2)

    print(
        f"  ✓ {file.name:30} "
        f"{size_mb:.2f} MB"
    )

print("\nTest Results:")
print(
    json.dumps(
        test_results,
        indent=4
    )
)

print("\n✓ FIQA checkpoint is safely stored in Google Drive.")

Mounted at /content/drive

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
✓ FIQA EXPERT SAVED TO GOOGLE DRIVE
============================================================

Location:
/content/drive/MyDrive/HACE_models/fiqa

Files:
  ✓ config.json                    0.00 MB
  ✓ model.safetensors              417.67 MB
  ✓ test_results.json              0.00 MB
  ✓ tokenizer.json                 0.68 MB
  ✓ tokenizer_config.json          0.00 MB
  ✓ training_history.csv           0.00 MB

Test Results:
{
    "accuracy": 0.7478260869565218,
    "macro_precision": 0.6318320970210762,
    "macro_recall": 0.5603897069760523,
    "macro_f1": 0.5789923906492351
}

✓ FIQA checkpoint is safely stored in Google Drive.

In [14]:
# ============================================================
# CELL 18 — GENERIC EXPERT TRAINING PIPELINE
# ============================================================

def prepare_expert_loaders(
    train_df,
    val_df,
    test_df=None,
    tokenizer=tokenizer,
    max_length=128,
    batch_size=16
):
    """
    Create PyTorch DataLoaders for an expert.
    """

    train_dataset = FinancialDataset(
        train_df,
        tokenizer,
        max_length
    )

    val_dataset = FinancialDataset(
        val_df,
        tokenizer,
        max_length
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=2,
        pin_memory=True
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=2,
        pin_memory=True
    )

    test_loader = None

    if test_df is not None:

        test_dataset = FinancialDataset(
            test_df,
            tokenizer,
            max_length
        )

        test_loader = DataLoader(
            test_dataset,
            batch_size=batch_size,
            shuffle=False,
            num_workers=2,
            pin_memory=True
        )

    return (
        train_loader,
        val_loader,
        test_loader
    )

In [34]:
# ============================================================
# CELL 19 — TWITTER EXPERT
# ============================================================

twitter_train_loader, twitter_val_loader, _ = (
    prepare_expert_loaders(
        twitter_train,
        twitter_val,
        None
    )
)

twitter_model = (
    AutoModelForSequenceClassification
    .from_pretrained(
        MODEL_NAME,
        num_labels=3,
        ignore_mismatched_sizes=True
    )
)

twitter_model.to(DEVICE)

twitter_checkpoint = (
    MODEL_DIR / "twitter_expert.pt"
)

twitter_model, twitter_history = train_model(
    model=twitter_model,
    train_loader=twitter_train_loader,
    val_loader=twitter_val_loader,
    device=DEVICE,
    epochs=EPOCHS,
    learning_rate=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
    save_path=twitter_checkpoint,
    patience=2
)

display(twitter_history)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

============================================================
TRAINING
============================================================

Epoch 1/3

Training:   0%|          | 0/597 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/150 [00:00<?, ?it/s]

Train Loss : 0.5231
Val Loss   : 0.3362
Val Acc    : 0.8781
Val F1     : 0.8313
Time       : 238.2s
✓ New best model (F1 = 0.8313)
✓ Checkpoint saved → /content/HACE_Financial_Sentiment_Analysis/models/twitter_expert.pt

Epoch 2/3

Training:   0%|          | 0/597 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/150 [00:00<?, ?it/s]

Train Loss : 0.2679
Val Loss   : 0.3318
Val Acc    : 0.8790
Val F1     : 0.8311
Time       : 237.6s
No improvement (1/2)

Epoch 3/3

Training:   0%|          | 0/597 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/150 [00:00<?, ?it/s]

Train Loss : 0.1353
Val Loss   : 0.3867
Val Acc    : 0.8698
Val F1     : 0.8328
Time       : 243.5s
✓ New best model (F1 = 0.8328)
✓ Checkpoint saved → /content/HACE_Financial_Sentiment_Analysis/models/twitter_expert.pt

============================================================
BEST VALIDATION F1: 0.8328
============================================================

,epoch,train_loss,val_loss,val_accuracy,val_precision,val_recall,val_f1,time_seconds
0,1,0.523146,0.336192,0.878141,0.843437,0.820375,0.831319,238.151345
1,2,0.267935,0.331848,0.878978,0.871743,0.800641,0.831113,237.616867
2,3,0.135262,0.386661,0.869765,0.818247,0.850313,0.832839,243.493780

In [35]:
# ============================================================
# CELL 20 — TWITTER EVALUATION
# ============================================================

twitter_metrics = evaluate_model(
    twitter_model,
    twitter_val_loader,
    DEVICE
)

print("=" * 60)
print("TWITTER EXPERT RESULTS")
print("=" * 60)

print(
    f"Accuracy : {twitter_metrics['accuracy']:.4f}"
)

print(
    f"Macro F1 : {twitter_metrics['f1']:.4f}"
)

print(
    classification_report(
        twitter_metrics["labels"],
        twitter_metrics["predictions"],
        target_names=[
            "Negative",
            "Neutral",
            "Positive"
        ],
        digits=4,
        zero_division=0
    )
)

Evaluating:   0%|          | 0/150 [00:00<?, ?it/s]

============================================================
TWITTER EXPERT RESULTS
============================================================
Accuracy : 0.8698
Macro F1 : 0.8328
              precision    recall  f1-score   support

    Negative     0.7229    0.8271    0.7715       347
     Neutral     0.8000    0.8337    0.8165       475
    Positive     0.9318    0.8902    0.9105      1566

    accuracy                         0.8698      2388
   macro avg     0.8182    0.8503    0.8328      2388
weighted avg     0.8752    0.8698    0.8716      2388

In [39]:
# ============================================================
# SAVE TWITTER EXPERT TO GOOGLE DRIVE — ONE CELL
# ============================================================

from pathlib import Path
import json

# ------------------------------------------------------------
# 1. Google Drive directory
# ------------------------------------------------------------

TWITTER_DIR = Path(
    "/content/drive/MyDrive/HACE_models/twitter"
)

TWITTER_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# 2. Save complete Hugging Face model
# ------------------------------------------------------------

twitter_model.save_pretrained(
    TWITTER_DIR,
    safe_serialization=True
)

# ------------------------------------------------------------
# 3. Save tokenizer
# ------------------------------------------------------------

tokenizer.save_pretrained(
    TWITTER_DIR
)

# ------------------------------------------------------------
# 4. Save training history
# ------------------------------------------------------------

twitter_history.to_csv(
    TWITTER_DIR / "training_history.csv",
    index=False
)

# ------------------------------------------------------------
# 5. Save evaluation results
# ------------------------------------------------------------

twitter_results = {
    "accuracy": float(
        twitter_metrics["accuracy"]
    ),
    "macro_precision": float(
        twitter_metrics["precision"]
    ),
    "macro_recall": float(
        twitter_metrics["recall"]
    ),
    "macro_f1": float(
        twitter_metrics["f1"]
    )
}

with open(
    TWITTER_DIR / "validation_results.json",
    "w"
) as f:
    json.dump(
        twitter_results,
        f,
        indent=4
    )

# ------------------------------------------------------------
# 6. Verify saved files
# ------------------------------------------------------------

print("=" * 60)
print("✓ TWITTER EXPERT SAVED TO GOOGLE DRIVE")
print("=" * 60)

print("\nLocation:")
print(TWITTER_DIR)

print("\nFiles:")

for file in sorted(TWITTER_DIR.iterdir()):
    size_mb = file.stat().st_size / (1024 ** 2)

    print(
        f"  ✓ {file.name:30} "
        f"{size_mb:.2f} MB"
    )

print("\nResults:")
print(
    json.dumps(
        twitter_results,
        indent=4
    )
)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
✓ TWITTER EXPERT SAVED TO GOOGLE DRIVE
============================================================

Location:
/content/drive/MyDrive/HACE_models/twitter

Files:
  ✓ config.json                    0.00 MB
  ✓ model.safetensors              417.67 MB
  ✓ tokenizer.json                 0.68 MB
  ✓ tokenizer_config.json          0.00 MB
  ✓ training_history.csv           0.00 MB
  ✓ validation_results.json        0.00 MB

Results:
{
    "accuracy": 0.8697654941373534,
    "macro_precision": 0.8182466987252881,
    "macro_recall": 0.850313191933057,
    "macro_f1": 0.8328387414391941
}

In [15]:
# ============================================================
# FINANCIAL PHRASEBANK EXPERT — TRAIN + EVALUATE + SAVE
# ============================================================

from pathlib import Path
import json

# ------------------------------------------------------------
# 1. Google Drive directory
# ------------------------------------------------------------

PHRASEBANK_DIR = Path(
    "/content/drive/MyDrive/HACE_models/phrasebank"
)

PHRASEBANK_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# 2. Prepare DataLoaders
# ------------------------------------------------------------

phrasebank_train_loader, phrasebank_val_loader, phrasebank_test_loader = (
    prepare_expert_loaders(
        phrasebank_train,
        phrasebank_val,
        phrasebank_test,
        tokenizer=tokenizer,
        max_length=MAX_LENGTH,
        batch_size=BATCH_SIZE
    )
)

print("Train samples:", len(phrasebank_train))
print("Validation samples:", len(phrasebank_val))
print("Test samples:", len(phrasebank_test))

# ------------------------------------------------------------
# 3. Create fresh FinBERT
# ------------------------------------------------------------

phrasebank_model = (
    AutoModelForSequenceClassification
    .from_pretrained(
        MODEL_NAME,
        num_labels=3,
        ignore_mismatched_sizes=True
    )
)

phrasebank_model.to(DEVICE)

# ------------------------------------------------------------
# 4. TRAIN
# ------------------------------------------------------------

phrasebank_model, phrasebank_history = train_model(
    model=phrasebank_model,
    train_loader=phrasebank_train_loader,
    val_loader=phrasebank_val_loader,
    device=DEVICE,
    epochs=EPOCHS,
    learning_rate=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
    save_path=None,
    patience=2
)

# ------------------------------------------------------------
# 5. TEST EVALUATION
# ------------------------------------------------------------

phrasebank_metrics = evaluate_model(
    phrasebank_model,
    phrasebank_test_loader,
    DEVICE
)

print("\n" + "=" * 60)
print("PHRASEBANK TEST RESULTS")
print("=" * 60)

print(
    f"Accuracy : {phrasebank_metrics['accuracy']:.4f}"
)

print(
    f"Precision: {phrasebank_metrics['precision']:.4f}"
)

print(
    f"Recall   : {phrasebank_metrics['recall']:.4f}"
)

print(
    f"Macro F1 : {phrasebank_metrics['f1']:.4f}"
)

print("\nClassification Report:\n")

print(
    classification_report(
        phrasebank_metrics["labels"],
        phrasebank_metrics["predictions"],
        target_names=[
            "Negative",
            "Neutral",
            "Positive"
        ],
        digits=4,
        zero_division=0
    )
)

# ------------------------------------------------------------
# 6. SAVE MODEL
# ------------------------------------------------------------

phrasebank_model.save_pretrained(
    PHRASEBANK_DIR,
    safe_serialization=True
)

# ------------------------------------------------------------
# 7. SAVE TOKENIZER
# ------------------------------------------------------------

tokenizer.save_pretrained(
    PHRASEBANK_DIR
)

# ------------------------------------------------------------
# 8. SAVE TRAINING HISTORY
# ------------------------------------------------------------

phrasebank_history.to_csv(
    PHRASEBANK_DIR / "training_history.csv",
    index=False
)

# ------------------------------------------------------------
# 9. SAVE TEST RESULTS
# ------------------------------------------------------------

phrasebank_results = {
    "accuracy": float(
        phrasebank_metrics["accuracy"]
    ),
    "macro_precision": float(
        phrasebank_metrics["precision"]
    ),
    "macro_recall": float(
        phrasebank_metrics["recall"]
    ),
    "macro_f1": float(
        phrasebank_metrics["f1"]
    )
}

with open(
    PHRASEBANK_DIR / "test_results.json",
    "w"
) as f:
    json.dump(
        phrasebank_results,
        f,
        indent=4
    )

# ------------------------------------------------------------
# 10. VERIFY
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("✓ PHRASEBANK EXPERT SAVED")
print("=" * 60)

print("\nLocation:")
print(PHRASEBANK_DIR)

print("\nFiles:")

for file in sorted(PHRASEBANK_DIR.iterdir()):
    size_mb = file.stat().st_size / (1024 ** 2)

    print(
        f"  ✓ {file.name:30} "
        f"{size_mb:.2f} MB"
    )

Train samples: 1807
Validation samples: 226
Test samples: 226

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

============================================================
TRAINING
============================================================

Epoch 1/3

Training:   0%|          | 0/113 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/15 [00:00<?, ?it/s]

Train Loss : 0.7099
Val Loss   : 0.1948
Val Acc    : 0.9558
Val F1     : 0.9319
Time       : 40.8s
✓ New best model (F1 = 0.9319)

Epoch 2/3

Training:   0%|          | 0/113 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/15 [00:00<?, ?it/s]

Train Loss : 0.1346
Val Loss   : 0.0885
Val Acc    : 0.9735
Val F1     : 0.9604
Time       : 49.8s
✓ New best model (F1 = 0.9604)

Epoch 3/3

Training:   0%|          | 0/113 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/15 [00:00<?, ?it/s]

Train Loss : 0.0563
Val Loss   : 0.0980
Val Acc    : 0.9646
Val F1     : 0.9593
Time       : 49.8s
No improvement (1/2)

============================================================
BEST VALIDATION F1: 0.9604
============================================================

Evaluating:   0%|          | 0/15 [00:00<?, ?it/s]

============================================================
PHRASEBANK TEST RESULTS
============================================================
Accuracy : 0.9558
Precision: 0.9222
Recall   : 0.9420
Macro F1 : 0.9309

Classification Report:

              precision    recall  f1-score   support

    Negative     0.8286    0.9355    0.8788        31
     Neutral     0.9926    0.9783    0.9854       138
    Positive     0.9455    0.9123    0.9286        57

    accuracy                         0.9558       226
   macro avg     0.9222    0.9420    0.9309       226
weighted avg     0.9582    0.9558    0.9564       226

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
✓ PHRASEBANK EXPERT SAVED
============================================================

Location:
/content/drive/MyDrive/HACE_models/phrasebank

Files:
  ✓ config.json                    0.00 MB
  ✓ model.safetensors              417.67 MB
  ✓ test_results.json              0.00 MB
  ✓ tokenizer.json                 0.68 MB
  ✓ tokenizer_config.json          0.00 MB
  ✓ training_history.csv           0.00 MB

In [16]:
# ============================================================
# FINANCE NEWS EXPERT — TRAIN + EVALUATE + SAVE TO DRIVE
# ============================================================

from pathlib import Path
import json

# ------------------------------------------------------------
# 1. Google Drive directory
# ------------------------------------------------------------

FINANCE_DIR = Path(
    "/content/drive/MyDrive/HACE_models/finance_news"
)

FINANCE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# 2. Prepare DataLoaders
# ------------------------------------------------------------

finance_train_loader, finance_val_loader, finance_test_loader = (
    prepare_expert_loaders(
        finance_news_train,
        finance_news_val,
        finance_news_test,
        tokenizer=tokenizer,
        max_length=MAX_LENGTH,
        batch_size=BATCH_SIZE
    )
)

print("Train samples:", len(finance_news_train))
print("Validation samples:", len(finance_news_val))
print("Test samples:", len(finance_news_test))

# ------------------------------------------------------------
# 3. Create fresh FinBERT
# ------------------------------------------------------------

finance_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=3,
    ignore_mismatched_sizes=True
)

finance_model.to(DEVICE)

# ------------------------------------------------------------
# 4. TRAIN
# ------------------------------------------------------------

finance_model, finance_history = train_model(
    model=finance_model,
    train_loader=finance_train_loader,
    val_loader=finance_val_loader,
    device=DEVICE,
    epochs=EPOCHS,
    learning_rate=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
    save_path=None,
    patience=2
)

# ------------------------------------------------------------
# 5. TEST EVALUATION
# ------------------------------------------------------------

finance_metrics = evaluate_model(
    finance_model,
    finance_test_loader,
    DEVICE
)

print("\n" + "=" * 60)
print("FINANCE NEWS TEST RESULTS")
print("=" * 60)

print(
    f"Accuracy : {finance_metrics['accuracy']:.4f}"
)

print(
    f"Precision: {finance_metrics['precision']:.4f}"
)

print(
    f"Recall   : {finance_metrics['recall']:.4f}"
)

print(
    f"Macro F1 : {finance_metrics['f1']:.4f}"
)

print("\nClassification Report:\n")

print(
    classification_report(
        finance_metrics["labels"],
        finance_metrics["predictions"],
        target_names=[
            "Negative",
            "Neutral",
            "Positive"
        ],
        digits=4,
        zero_division=0
    )
)

# ------------------------------------------------------------
# 6. SAVE MODEL
# ------------------------------------------------------------

finance_model.save_pretrained(
    FINANCE_DIR,
    safe_serialization=True
)

# ------------------------------------------------------------
# 7. SAVE TOKENIZER
# ------------------------------------------------------------

tokenizer.save_pretrained(
    FINANCE_DIR
)

# ------------------------------------------------------------
# 8. SAVE TRAINING HISTORY
# ------------------------------------------------------------

finance_history.to_csv(
    FINANCE_DIR / "training_history.csv",
    index=False
)

# ------------------------------------------------------------
# 9. SAVE TEST RESULTS
# ------------------------------------------------------------

finance_results = {
    "accuracy": float(
        finance_metrics["accuracy"]
    ),
    "macro_precision": float(
        finance_metrics["precision"]
    ),
    "macro_recall": float(
        finance_metrics["recall"]
    ),
    "macro_f1": float(
        finance_metrics["f1"]
    )
}

with open(
    FINANCE_DIR / "test_results.json",
    "w"
) as f:
    json.dump(
        finance_results,
        f,
        indent=4
    )

# ------------------------------------------------------------
# 10. VERIFY
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("✓ FINANCE NEWS EXPERT SAVED")
print("=" * 60)

print("\nLocation:")
print(FINANCE_DIR)

print("\nFiles:")

for file in sorted(FINANCE_DIR.iterdir()):
    size_mb = file.stat().st_size / (1024 ** 2)

    print(
        f"  ✓ {file.name:30} "
        f"{size_mb:.2f} MB"
    )

Train samples: 25928
Validation samples: 3241
Test samples: 3241

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

============================================================
TRAINING
============================================================

Epoch 1/3

Training:   0%|          | 0/1621 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/203 [00:00<?, ?it/s]

Train Loss : 0.7634
Val Loss   : 0.6054
Val Acc    : 0.7353
Val F1     : 0.7308
Time       : 575.7s
✓ New best model (F1 = 0.7308)

Epoch 2/3

Training:   0%|          | 0/1621 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/203 [00:00<?, ?it/s]

Train Loss : 0.5018
Val Loss   : 0.5742
Val Acc    : 0.7442
Val F1     : 0.7449
Time       : 586.7s
✓ New best model (F1 = 0.7449)

Epoch 3/3

Training:   0%|          | 0/1621 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/203 [00:00<?, ?it/s]

Train Loss : 0.3486
Val Loss   : 0.6981
Val Acc    : 0.7390
Val F1     : 0.7406
Time       : 586.2s
No improvement (1/2)

============================================================
BEST VALIDATION F1: 0.7449
============================================================

Evaluating:   0%|          | 0/203 [00:00<?, ?it/s]

============================================================
FINANCE NEWS TEST RESULTS
============================================================
Accuracy : 0.7442
Precision: 0.7576
Recall   : 0.7444
Macro F1 : 0.7451

Classification Report:

              precision    recall  f1-score   support

    Negative     0.6428    0.8115    0.7173      1082
     Neutral     0.8856    0.8065    0.8442      1075
    Positive     0.7444    0.6153    0.6737      1084

    accuracy                         0.7442      3241
   macro avg     0.7576    0.7444    0.7451      3241
weighted avg     0.7573    0.7442    0.7448      3241

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
✓ FINANCE NEWS EXPERT SAVED
============================================================

Location:
/content/drive/MyDrive/HACE_models/finance_news

Files:
  ✓ config.json                    0.00 MB
  ✓ model.safetensors              417.67 MB
  ✓ test_results.json              0.00 MB
  ✓ tokenizer.json                 0.68 MB
  ✓ tokenizer_config.json          0.00 MB
  ✓ training_history.csv           0.00 MB