In [35]:
# ============================================================
# CELL 1 — GOOGLE DRIVE
# ============================================================

from google.colab import drive
from pathlib import Path

DRIVE_ROOT = Path("/content/drive/MyDrive")

if not DRIVE_ROOT.exists():
    drive.mount("/content/drive")
else:
    print("✓ Google Drive already mounted")

print("Drive:", DRIVE_ROOT)
print("✓ Drive ready")

✓ Google Drive already mounted
Drive: /content/drive/MyDrive
✓ Drive ready

In [36]:
# ============================================================
# CELL 2 — LOAD HACE REPOSITORY
# ============================================================

import os
from pathlib import Path

REPO_DIR = Path("/content/HACE_Financial_Sentiment_Analysis")

if REPO_DIR.exists():
    print("✓ Repository already exists")
else:
    !git clone https://github.com/your-username/HACE_Financial_Sentiment_Analysis.git /content/HACE_Financial_Sentiment_Analysis
    print("✓ Repository cloned")

os.chdir(REPO_DIR)

print("Working directory:")
print(Path.cwd())

✓ Repository already exists
Working directory:
/content/HACE_Financial_Sentiment_Analysis

In [37]:
# ============================================================
# CELL 3 — DEPENDENCIES
# ============================================================

import sys
import torch
import numpy as np
import pandas as pd

print("Python:", sys.version)
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print("\n✓ Dependencies ready")
print("Device:", DEVICE)

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
PyTorch: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4

✓ Dependencies ready
Device: cuda

In [38]:
# ============================================================
# CELL 4 — MODEL PATHS
# ============================================================

from pathlib import Path

DRIVE_MODEL_DIR = Path(
    "/content/drive/MyDrive/HACE_models"
)

ACTIVE_EXPERT_KEYS = [
    "fiqa",
    "phrasebank",
    "twitter",
    "finance_news",
    "general",
]

DOMAIN_PATHS = {
    "fiqa":
        DRIVE_MODEL_DIR / "fiqa",

    "phrasebank":
        DRIVE_MODEL_DIR / "phrasebank",

    "twitter":
        DRIVE_MODEL_DIR / "twitter",

    "finance_news":
        DRIVE_MODEL_DIR / "finance_news",

    "general":
        DRIVE_MODEL_DIR / "general_finbert",
}


print("=" * 60)
print("EXPERT MODEL DIRECTORIES")
print("=" * 60)

for key in ACTIVE_EXPERT_KEYS:

    path = DOMAIN_PATHS[key]

    status = "FOUND" if path.exists() else "MISSING"

    print(f"{key:15} : {status}")
    print(f"                 {path}")

print("\n✓ Path verification complete")

============================================================
EXPERT MODEL DIRECTORIES
============================================================
fiqa            : FOUND
                 /content/drive/MyDrive/HACE_models/fiqa
phrasebank      : FOUND
                 /content/drive/MyDrive/HACE_models/phrasebank
twitter         : FOUND
                 /content/drive/MyDrive/HACE_models/twitter
finance_news    : FOUND
                 /content/drive/MyDrive/HACE_models/finance_news
general         : FOUND
                 /content/drive/MyDrive/HACE_models/general_finbert

✓ Path verification complete

In [39]:
# ============================================================
# CELL 5 — LOAD ALL 5 EXPERTS
# ============================================================

from src.models.finbert_expert import FinBERTExpert

print("=" * 60)
print("LOADING 5 FINBERT EXPERTS")
print("=" * 60)

experts = {}

for key in ACTIVE_EXPERT_KEYS:

    model_path = DOMAIN_PATHS[key]

    print(f"\nLoading: {key}")
    print(f"Path: {model_path}")

    experts[key] = FinBERTExpert(
        model_path=model_path,
        domain=key,
        device=DEVICE
    )

    print(f"✓ {key} loaded")


# ============================================================
# FINAL VERIFICATION
# ============================================================

print("\n" + "=" * 60)
print("EXPERT LOADING COMPLETE")
print("=" * 60)

print("Loaded experts:")

for key in experts:
    print(f"✓ {key}")

print("\nTotal experts:", len(experts))

assert len(experts) == 5

print("\n✓ ALL 5 EXPERTS LOADED SUCCESSFULLY")

============================================================
LOADING 5 FINBERT EXPERTS
============================================================

Loading: fiqa
Path: /content/drive/MyDrive/HACE_models/fiqa

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

✓ fiqa loaded

Loading: phrasebank
Path: /content/drive/MyDrive/HACE_models/phrasebank

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

✓ phrasebank loaded

Loading: twitter
Path: /content/drive/MyDrive/HACE_models/twitter

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

✓ twitter loaded

Loading: finance_news
Path: /content/drive/MyDrive/HACE_models/finance_news

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

✓ finance_news loaded

Loading: general
Path: /content/drive/MyDrive/HACE_models/general_finbert

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

✓ general loaded

============================================================
EXPERT LOADING COMPLETE
============================================================
Loaded experts:
✓ fiqa
✓ phrasebank
✓ twitter
✓ finance_news
✓ general

Total experts: 5

✓ ALL 5 EXPERTS LOADED SUCCESSFULLY

In [40]:
# ============================================================
# CELL 6 — LOAD META DATASET
# ============================================================

import pandas as pd

# Update these paths if your repository stores the files elsewhere
META_TRAIN_PATH = REPO_DIR / "data" / "processed" / "meta_train.csv"
META_TEST_PATH  = REPO_DIR / "data" / "processed" / "meta_test.csv"

print("=" * 60)
print("LOADING META DATASET")
print("=" * 60)

print("Train path:", META_TRAIN_PATH)
print("Test path :", META_TEST_PATH)

meta_train = pd.read_csv(META_TRAIN_PATH)
meta_test = pd.read_csv(META_TEST_PATH)

print("\n✓ Meta datasets loaded")

print("\nTrain shape:", meta_train.shape)
print("Test shape :", meta_test.shape)

print("\nColumns:")
print(meta_train.columns.tolist())

print("\nTrain sample:")
display(meta_train.head())

============================================================
LOADING META DATASET
============================================================
Train path: /content/HACE_Financial_Sentiment_Analysis/data/processed/meta_train.csv
Test path : /content/HACE_Financial_Sentiment_Analysis/data/processed/meta_test.csv

FileNotFoundError: [Errno 2] No such file or directory: '/content/HACE_Financial_Sentiment_Analysis/data/processed/meta_train.csv'

In [41]:
# ============================================================
# CELL 7 — VERIFY META DATA
# ============================================================

print("=" * 60)
print("META DATA SANITY CHECK")
print("=" * 60)

# Required columns
assert "text" in meta_train.columns
assert "label" in meta_train.columns

assert "text" in meta_test.columns
assert "label" in meta_test.columns

# Missing values
print("\nMissing values:")

print("\nTrain:")
print(meta_train[["text", "label"]].isna().sum())

print("\nTest:")
print(meta_test[["text", "label"]].isna().sum())

# Label distribution
print("\n" + "=" * 60)
print("LABEL DISTRIBUTION")
print("=" * 60)

print("\nTrain:")
print(meta_train["label"].value_counts().sort_index())

print("\nTest:")
print(meta_test["label"].value_counts().sort_index())

# Basic checks
assert meta_train["text"].notna().all()
assert meta_test["text"].notna().all()

assert meta_train["label"].notna().all()
assert meta_test["label"].notna().all()

print("\n✓ Dataset sanity checks passed")

============================================================
META DATA SANITY CHECK
============================================================

Missing values:

Train:
text     0
label    0
dtype: int64

Test:
text     0
label    0
dtype: int64

============================================================
LABEL DISTRIBUTION
============================================================

Train:
label
0    1498
1    1698
2    2770
Name: count, dtype: int64

Test:
label
0    1196
1    1225
2    1276
Name: count, dtype: int64

✓ Dataset sanity checks passed

In [42]:
# ============================================================
# CELL 8 — TEST ALL 5 EXPERTS
# ============================================================

print("=" * 60)
print("TESTING ALL 5 EXPERTS")
print("=" * 60)

sample_text = str(meta_train.iloc[0]["text"])

print("\nSample:")
print(sample_text)

print("\n" + "-" * 60)

for key in ACTIVE_EXPERT_KEYS:

    probabilities = experts[key].predict_proba(
        sample_text
    )

    print(f"\n{key}:")
    print("  Negative:", round(float(probabilities[0]), 4))
    print("  Neutral :", round(float(probabilities[1]), 4))
    print("  Positive:", round(float(probabilities[2]), 4))
    print("  Sum     :", round(float(sum(probabilities)), 4))

    assert len(probabilities) == 3
    assert abs(sum(probabilities) - 1.0) < 1e-4

print("\n✓ All 5 experts passed inference test")

============================================================
TESTING ALL 5 EXPERTS
============================================================

Sample:
S&P downgrades Barclays and RBS on government bailout fears

------------------------------------------------------------

fiqa:
  Negative: 0.6464
  Neutral : 0.3172
  Positive: 0.0364
  Sum     : 1.0

phrasebank:
  Negative: 0.3004
  Neutral : 0.678
  Positive: 0.0216
  Sum     : 1.0

twitter:
  Negative: 0.9784
  Neutral : 0.0037
  Positive: 0.0178
  Sum     : 1.0

finance_news:
  Negative: 0.9419
  Neutral : 0.0086
  Positive: 0.0495
  Sum     : 1.0

general:
  Negative: 0.0094
  Neutral : 0.9555
  Positive: 0.0351
  Sum     : 1.0

✓ All 5 experts passed inference test

In [43]:
# ============================================================
# CELL 9 — GENERATE 5-EXPERT PREDICTIONS
# ============================================================

print("=" * 60)
print("GENERATING 5-EXPERT PREDICTIONS")
print("=" * 60)


def generate_expert_predictions(df):

    rows = []

    total = len(df)

    for i, text in enumerate(df["text"]):

        row = {}

        for key in ACTIVE_EXPERT_KEYS:

            probabilities = experts[key].predict_proba(
                str(text)
            )

            row[f"{key}_neg"] = float(probabilities[0])
            row[f"{key}_neu"] = float(probabilities[1])
            row[f"{key}_pos"] = float(probabilities[2])

        rows.append(row)

        # Progress
        if (i + 1) % 500 == 0 or i + 1 == total:
            print(
                f"Processed {i + 1}/{total} "
                f"({100 * (i + 1) / total:.1f}%)"
            )

    return pd.DataFrame(
        rows,
        index=df.index
    )


# ------------------------------------------------------------
# TRAIN
# ------------------------------------------------------------

print("\nGenerating TRAIN predictions...")

train_expert_df = generate_expert_predictions(
    meta_train
)

print("\n✓ Training predictions generated")
print("Shape:", train_expert_df.shape)


# ------------------------------------------------------------
# TEST
# ------------------------------------------------------------

print("\nGenerating TEST predictions...")

test_expert_df = generate_expert_predictions(
    meta_test
)

print("\n✓ Test predictions generated")
print("Shape:", test_expert_df.shape)

============================================================
GENERATING 5-EXPERT PREDICTIONS
============================================================

Generating TRAIN predictions...
Processed 500/5966 (8.4%)
Processed 1000/5966 (16.8%)
Processed 1500/5966 (25.1%)
Processed 2000/5966 (33.5%)
Processed 2500/5966 (41.9%)
Processed 3000/5966 (50.3%)
Processed 3500/5966 (58.7%)
Processed 4000/5966 (67.0%)
Processed 4500/5966 (75.4%)
Processed 5000/5966 (83.8%)
Processed 5500/5966 (92.2%)
Processed 5966/5966 (100.0%)

✓ Training predictions generated
Shape: (5966, 15)

Generating TEST predictions...
Processed 500/3697 (13.5%)
Processed 1000/3697 (27.0%)
Processed 1500/3697 (40.6%)
Processed 2000/3697 (54.1%)
Processed 2500/3697 (67.6%)
Processed 3000/3697 (81.1%)
Processed 3500/3697 (94.7%)
Processed 3697/3697 (100.0%)

✓ Test predictions generated
Shape: (3697, 15)

In [44]:
# ============================================================
# CELL 10 — VERIFY EXPERT PREDICTIONS
# ============================================================

print("=" * 60)
print("EXPERT PREDICTION VERIFICATION")
print("=" * 60)

print("\nTrain shape:")
print(train_expert_df.shape)

print("\nTest shape:")
print(test_expert_df.shape)


# ------------------------------------------------------------
# EXPECTED COLUMNS
# ------------------------------------------------------------

expected_columns = []

for key in ACTIVE_EXPERT_KEYS:

    expected_columns.extend([
        f"{key}_neg",
        f"{key}_neu",
        f"{key}_pos",
    ])

print("\nExpected columns:")
print(expected_columns)

print("\nActual columns:")
print(train_expert_df.columns.tolist())


# ------------------------------------------------------------
# ASSERTIONS
# ------------------------------------------------------------

assert train_expert_df.shape[1] == 15
assert test_expert_df.shape[1] == 15

assert train_expert_df.columns.tolist() == expected_columns
assert test_expert_df.columns.tolist() == expected_columns

assert len(train_expert_df) == len(meta_train)
assert len(test_expert_df) == len(meta_test)


# ------------------------------------------------------------
# CHECK PROBABILITY SUMS
# ------------------------------------------------------------

for key in ACTIVE_EXPERT_KEYS:

    cols = [
        f"{key}_neg",
        f"{key}_neu",
        f"{key}_pos",
    ]

    train_sums = train_expert_df[cols].sum(axis=1)
    test_sums = test_expert_df[cols].sum(axis=1)

    assert np.allclose(
        train_sums,
        1.0,
        atol=1e-4
    )

    assert np.allclose(
        test_sums,
        1.0,
        atol=1e-4
    )


print("\n✓ All 5 experts present")
print("✓ 15 probability features confirmed")
print("✓ Train/test alignment confirmed")
print("✓ Probability distributions valid")

print("\nFirst 5 rows:")
display(train_expert_df.head())

============================================================
EXPERT PREDICTION VERIFICATION
============================================================

Train shape:
(5966, 15)

Test shape:
(3697, 15)

Expected columns:
['fiqa_neg', 'fiqa_neu', 'fiqa_pos', 'phrasebank_neg', 'phrasebank_neu', 'phrasebank_pos', 'twitter_neg', 'twitter_neu', 'twitter_pos', 'finance_news_neg', 'finance_news_neu', 'finance_news_pos', 'general_neg', 'general_neu', 'general_pos']

Actual columns:
['fiqa_neg', 'fiqa_neu', 'fiqa_pos', 'phrasebank_neg', 'phrasebank_neu', 'phrasebank_pos', 'twitter_neg', 'twitter_neu', 'twitter_pos', 'finance_news_neg', 'finance_news_neu', 'finance_news_pos', 'general_neg', 'general_neu', 'general_pos']

✓ All 5 experts present
✓ 15 probability features confirmed
✓ Train/test alignment confirmed
✓ Probability distributions valid

First 5 rows:

,fiqa_neg,fiqa_neu,fiqa_pos,phrasebank_neg,phrasebank_neu,phrasebank_pos,twitter_neg,twitter_neu,twitter_pos,finance_news_neg,finance_news_neu,finance_news_pos,general_neg,general_neu,general_pos
0,0.646407,0.317218,0.036375,0.300389,0.678007,0.021604,0.978410,0.003745,0.017845,0.941877,0.008624,0.049499,0.009405,0.955481,0.035114
1,0.027574,0.021091,0.951336,0.001994,0.995276,0.002730,0.004319,0.002617,0.993064,0.069496,0.924063,0.006441,0.048033,0.019163,0.932803
2,0.747095,0.203925,0.048980,0.043417,0.945617,0.010966,0.940450,0.010283,0.049267,0.959229,0.023479,0.017292,0.015575,0.942904,0.041521
3,0.035771,0.538644,0.425586,0.001802,0.995093,0.003104,0.002918,0.004233,0.992848,0.004071,0.994211,0.001718,0.032184,0.041605,0.926211
4,0.054841,0.086600,0.858559,0.032307,0.003661,0.964032,0.005116,0.903717,0.091167,0.026661,0.053121,0.920218,0.934796,0.022467,0.042737

In [45]:
# ============================================================
# CELL 11 — CONVERT EXPERT PREDICTIONS
# ============================================================

import numpy as np

print("=" * 60)
print("CONVERTING EXPERT PREDICTIONS")
print("=" * 60)


def dataframe_to_expert_probas(df):

    expert_probas = []

    for _, row in df.iterrows():

        sample = {}

        for key in ACTIVE_EXPERT_KEYS:

            sample[key] = [
                float(row[f"{key}_neg"]),
                float(row[f"{key}_neu"]),
                float(row[f"{key}_pos"]),
            ]

        expert_probas.append(sample)

    return expert_probas


train_expert_probas = dataframe_to_expert_probas(
    train_expert_df
)

test_expert_probas = dataframe_to_expert_probas(
    test_expert_df
)

print("✓ Train expert probabilities converted")
print("✓ Test expert probabilities converted")

print("\nTrain samples:", len(train_expert_probas))
print("Test samples :", len(test_expert_probas))

print("\nExample:")
print(train_expert_probas[0])

============================================================
CONVERTING EXPERT PREDICTIONS
============================================================
✓ Train expert probabilities converted
✓ Test expert probabilities converted

Train samples: 5966
Test samples : 3697

Example:
{'fiqa': [0.6464073061943054, 0.31721797585487366, 0.03637475147843361], 'phrasebank': [0.3003886342048645, 0.678007185459137, 0.021604182198643684], 'twitter': [0.9784095883369446, 0.0037453635595738888, 0.0178450308740139], 'finance_news': [0.9418768882751465, 0.008624136447906494, 0.049498964101076126], 'general': [0.009405439719557762, 0.9554807543754578, 0.03511383756995201]}

In [46]:
# ============================================================
# CELL 12 — HACE COMPONENTS
# ============================================================

from src.ensemble.feature_fusion import FeatureFusion
from src.hedging.detector import HedgeDetector

print("=" * 60)
print("LOADING HACE COMPONENTS")
print("=" * 60)


# ------------------------------------------------------------
# BASE FUSION
# ------------------------------------------------------------

base_fusion = FeatureFusion(
    use_hedge_features=False
)


# ------------------------------------------------------------
# HACE FUSION
# ------------------------------------------------------------

hace_fusion = FeatureFusion(
    use_hedge_features=True
)


# ------------------------------------------------------------
# HEDGE DETECTOR
# ------------------------------------------------------------

hedge_detector = HedgeDetector()


print("\nBase features:", len(base_fusion.feature_names))
print("HACE features:", len(hace_fusion.feature_names))

print("\nHedge detector:", type(hedge_detector).__name__)

assert len(base_fusion.feature_names) == 18
assert len(hace_fusion.feature_names) == 21

print("\n✓ HACE components ready")

============================================================
LOADING HACE COMPONENTS
============================================================

Base features: 18
HACE features: 21

Hedge detector: HedgeDetector

✓ HACE components ready

In [47]:
# ============================================================
# CELL 13 — GENERATE HEDGE FEATURES
# ============================================================

print("=" * 60)
print("GENERATING HEDGE FEATURES")
print("=" * 60)


train_texts = meta_train["text"].astype(str).tolist()
test_texts = meta_test["text"].astype(str).tolist()


# ------------------------------------------------------------
# TRAIN HEDGE FEATURES
# ------------------------------------------------------------

print("\nProcessing training texts...")

train_hedge_features = [
    hedge_detector.detect(text)
    for text in train_texts
]


# ------------------------------------------------------------
# TEST HEDGE FEATURES
# ------------------------------------------------------------

print("Processing test texts...")

test_hedge_features = [
    hedge_detector.detect(text)
    for text in test_texts
]


print("\n✓ Training hedge features:", len(train_hedge_features))
print("✓ Test hedge features:", len(test_hedge_features))


# ------------------------------------------------------------
# CHECK HEDGE DETECTION
# ------------------------------------------------------------

hedged_train = sum(
    hf.hedge_flag
    for hf in train_hedge_features
)

hedged_test = sum(
    hf.hedge_flag
    for hf in test_hedge_features
)


print("\nHedge statistics:")
print(
    f"Train hedged: {hedged_train}/{len(train_hedge_features)} "
    f"({100 * hedged_train / len(train_hedge_features):.2f}%)"
)

print(
    f"Test hedged : {hedged_test}/{len(test_hedge_features)} "
    f"({100 * hedged_test / len(test_hedge_features):.2f}%)"
)


print("\nExample hedge features:")

for hf in train_hedge_features[:5]:
    print(hf)

============================================================
GENERATING HEDGE FEATURES
============================================================

Processing training texts...
Processing test texts...

✓ Training hedge features: 5966
✓ Test hedge features: 3697

Hedge statistics:
Train hedged: 693/5966 (11.62%)
Test hedged : 495/3697 (13.39%)

Example hedge features:
HedgeFeatures(hedge_flag=False, hedge_probability=0, detected_terms=[], hedge_count=0, hedge_density=0.0, hedge_categories={})
HedgeFeatures(hedge_flag=False, hedge_probability=0, detected_terms=[], hedge_count=0, hedge_density=0.0, hedge_categories={})
HedgeFeatures(hedge_flag=False, hedge_probability=0, detected_terms=[], hedge_count=0, hedge_density=0.0, hedge_categories={})
HedgeFeatures(hedge_flag=False, hedge_probability=0, detected_terms=[], hedge_count=0, hedge_density=0.0, hedge_categories={})
HedgeFeatures(hedge_flag=False, hedge_probability=0, detected_terms=[], hedge_count=0, hedge_density=0.0, hedge_categories={})

In [48]:
# ============================================================
# CELL 14 — BUILD BASE + HACE FEATURES
# ============================================================

print("=" * 60)
print("BUILDING META-LEARNER FEATURE MATRICES")
print("=" * 60)


# ------------------------------------------------------------
# BASE ENSEMBLE
# ------------------------------------------------------------

X_base_train = base_fusion.assemble_batch(
    train_expert_probas,
    texts=train_texts
)

X_base_test = base_fusion.assemble_batch(
    test_expert_probas,
    texts=test_texts
)


# ------------------------------------------------------------
# HACE
# ------------------------------------------------------------

X_hace_train = hace_fusion.assemble_batch(
    train_expert_probas,
    hedge_features_list=train_hedge_features,
    texts=train_texts
)

X_hace_test = hace_fusion.assemble_batch(
    test_expert_probas,
    hedge_features_list=test_hedge_features,
    texts=test_texts
)


# ------------------------------------------------------------
# SHAPES
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("FEATURE MATRIX SHAPES")
print("=" * 60)

print("X_base_train :", X_base_train.shape)
print("X_base_test  :", X_base_test.shape)

print("X_hace_train :", X_hace_train.shape)
print("X_hace_test  :", X_hace_test.shape)


# ------------------------------------------------------------
# ASSERTIONS
# ------------------------------------------------------------

assert X_base_train.shape == (len(meta_train), 18)
assert X_base_test.shape == (len(meta_test), 18)

assert X_hace_train.shape == (len(meta_train), 21)
assert X_hace_test.shape == (len(meta_test), 21)

print("\n✓ Base feature matrix valid")
print("✓ HACE feature matrix valid")

============================================================
BUILDING META-LEARNER FEATURE MATRICES
============================================================

============================================================
FEATURE MATRIX SHAPES
============================================================
X_base_train : (5966, 18)
X_base_test  : (3697, 18)
X_hace_train : (5966, 21)
X_hace_test  : (3697, 21)

✓ Base feature matrix valid
✓ HACE feature matrix valid

In [49]:
# ============================================================
# CELL 15 — LABELS + FINAL SANITY CHECK
# ============================================================

print("=" * 60)
print("FINAL ENSEMBLE DATA CHECK")
print("=" * 60)


# ------------------------------------------------------------
# LABELS
# ------------------------------------------------------------

y_train = meta_train["label"].to_numpy(
    dtype=np.int64
)

y_test = meta_test["label"].to_numpy(
    dtype=np.int64
)


# ------------------------------------------------------------
# SHAPES
# ------------------------------------------------------------

print("\nLabels:")
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)


# ------------------------------------------------------------
# CLASS DISTRIBUTION
# ------------------------------------------------------------

print("\nTrain distribution:")
print(np.bincount(y_train))

print("\nTest distribution:")
print(np.bincount(y_test))


# ------------------------------------------------------------
# ALIGNMENT
# ------------------------------------------------------------

assert len(X_base_train) == len(y_train)
assert len(X_base_test) == len(y_test)

assert len(X_hace_train) == len(y_train)
assert len(X_hace_test) == len(y_test)


# ------------------------------------------------------------
# FINITE VALUE CHECK
# ------------------------------------------------------------

assert np.isfinite(X_base_train).all()
assert np.isfinite(X_base_test).all()

assert np.isfinite(X_hace_train).all()
assert np.isfinite(X_hace_test).all()


# ------------------------------------------------------------
# FINAL SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("ENSEMBLE DATA READY")
print("=" * 60)

print("Experts              :", len(ACTIVE_EXPERT_KEYS))
print("Expert probabilities :", 15)
print("Base features        :", X_base_train.shape[1])
print("HACE features        :", X_hace_train.shape[1])
print("Train samples        :", len(y_train))
print("Test samples         :", len(y_test))

print("\n✓ ALL SANITY CHECKS PASSED")

============================================================
FINAL ENSEMBLE DATA CHECK
============================================================

Labels:
y_train: (5966,)
y_test : (3697,)

Train distribution:
[1498 1698 2770]

Test distribution:
[1196 1225 1276]

============================================================
ENSEMBLE DATA READY
============================================================
Experts              : 5
Expert probabilities : 15
Base features        : 18
HACE features        : 21
Train samples        : 5966
Test samples         : 3697

✓ ALL SANITY CHECKS PASSED

In [50]:
# ============================================================
# CELL 16 — INDIVIDUAL EXPERT BASELINES
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("=" * 60)
print("INDIVIDUAL EXPERT BASELINES")
print("=" * 60)

expert_results = []


for key in ACTIVE_EXPERT_KEYS:

    neg_col = f"{key}_neg"
    neu_col = f"{key}_neu"
    pos_col = f"{key}_pos"

    proba = test_expert_df[
        [neg_col, neu_col, pos_col]
    ].to_numpy()

    pred = np.argmax(proba, axis=1)

    expert_results.append({
        "Model": key,
        "Accuracy": accuracy_score(y_test, pred),
        "Macro Precision": precision_score(
            y_test,
            pred,
            average="macro",
            zero_division=0
        ),
        "Macro Recall": recall_score(
            y_test,
            pred,
            average="macro",
            zero_division=0
        ),
        "Macro F1": f1_score(
            y_test,
            pred,
            average="macro",
            zero_division=0
        )
    })


expert_results_df = pd.DataFrame(expert_results)

print("\n")
display(
    expert_results_df.sort_values(
        "Macro F1",
        ascending=False
    ).reset_index(drop=True)
)

============================================================
INDIVIDUAL EXPERT BASELINES
============================================================

          Model  Accuracy  Macro Precision  Macro Recall  Macro F1
0  finance_news  0.751691         0.752288      0.753311  0.749974
1    phrasebank  0.466324         0.622052      0.465990  0.423792
2          fiqa  0.413308         0.385146      0.407143  0.340612
3       twitter  0.304301         0.384581      0.301142  0.288609
4       general  0.225588         0.194720      0.221215  0.197428

In [51]:
# ============================================================
# CELL 17 — SIMPLE AVERAGE ENSEMBLE
# ============================================================

print("=" * 60)
print("SIMPLE PROBABILITY ENSEMBLE")
print("=" * 60)


expert_probability_arrays = []

for key in ACTIVE_EXPERT_KEYS:

    cols = [
        f"{key}_neg",
        f"{key}_neu",
        f"{key}_pos"
    ]

    expert_probability_arrays.append(
        test_expert_df[cols].to_numpy()
    )


# Shape:
# (5, 3697, 3)

expert_probability_arrays = np.stack(
    expert_probability_arrays,
    axis=0
)


# Equal-weight average
avg_proba = np.mean(
    expert_probability_arrays,
    axis=0
)

avg_pred = np.argmax(
    avg_proba,
    axis=1
)


avg_accuracy = accuracy_score(
    y_test,
    avg_pred
)

avg_precision = precision_score(
    y_test,
    avg_pred,
    average="macro",
    zero_division=0
)

avg_recall = recall_score(
    y_test,
    avg_pred,
    average="macro",
    zero_division=0
)

avg_f1 = f1_score(
    y_test,
    avg_pred,
    average="macro",
    zero_division=0
)


print(f"\nAccuracy       : {avg_accuracy:.4f}")
print(f"Macro Precision: {avg_precision:.4f}")
print(f"Macro Recall   : {avg_recall:.4f}")
print(f"Macro F1       : {avg_f1:.4f}")

============================================================
SIMPLE PROBABILITY ENSEMBLE
============================================================

Accuracy       : 0.4371
Macro Precision: 0.5309
Macro Recall   : 0.4302
Macro F1       : 0.3939

In [52]:
# ============================================================
# CELL 18 — BASE META-LEARNER
# ============================================================

from src.ensemble.meta_learner import MetaLearner

print("=" * 60)
print("BASE META-LEARNER")
print("=" * 60)

base_meta = MetaLearner(
    use_hedge_features=False,
    C=1.0,
    max_iter=1000
)

base_meta.fit(
    X_base_train,
    y_train
)

base_pred = base_meta.predict(
    X_base_test
)

base_proba = base_meta.predict_proba(
    X_base_test
)


base_accuracy = accuracy_score(
    y_test,
    base_pred
)

base_precision = precision_score(
    y_test,
    base_pred,
    average="macro",
    zero_division=0
)

base_recall = recall_score(
    y_test,
    base_pred,
    average="macro",
    zero_division=0
)

base_f1 = f1_score(
    y_test,
    base_pred,
    average="macro",
    zero_division=0
)


print(f"\nAccuracy       : {base_accuracy:.4f}")
print(f"Macro Precision: {base_precision:.4f}")
print(f"Macro Recall   : {base_recall:.4f}")
print(f"Macro F1       : {base_f1:.4f}")

============================================================
BASE META-LEARNER
============================================================

Accuracy       : 0.5594
Macro Precision: 0.6308
Macro Recall   : 0.5591
Macro F1       : 0.5406

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [53]:
# ============================================================
# CELL 19 — HACE META-LEARNER
# ============================================================

print("=" * 60)
print("HACE META-LEARNER")
print("=" * 60)

hace_meta = MetaLearner(
    use_hedge_features=True,
    C=1.0,
    max_iter=1000
)

hace_meta.fit(
    X_hace_train,
    y_train
)

hace_pred = hace_meta.predict(
    X_hace_test
)

hace_proba = hace_meta.predict_proba(
    X_hace_test
)


hace_accuracy = accuracy_score(
    y_test,
    hace_pred
)

hace_precision = precision_score(
    y_test,
    hace_pred,
    average="macro",
    zero_division=0
)

hace_recall = recall_score(
    y_test,
    hace_pred,
    average="macro",
    zero_division=0
)

hace_f1 = f1_score(
    y_test,
    hace_pred,
    average="macro",
    zero_division=0
)


print(f"\nAccuracy       : {hace_accuracy:.4f}")
print(f"Macro Precision: {hace_precision:.4f}")
print(f"Macro Recall   : {hace_recall:.4f}")
print(f"Macro F1       : {hace_f1:.4f}")

============================================================
HACE META-LEARNER
============================================================

Accuracy       : 0.5637
Macro Precision: 0.6291
Macro Recall   : 0.5636
Macro F1       : 0.5475

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [54]:
# ============================================================
# CELL 20 — COMPLETE MODEL COMPARISON
# ============================================================

print("=" * 60)
print("MODEL COMPARISON")
print("=" * 60)


comparison_rows = []

# Individual experts
for _, row in expert_results_df.iterrows():

    comparison_rows.append({
        "Model": row["Model"],
        "Accuracy": row["Accuracy"],
        "Macro Precision": row["Macro Precision"],
        "Macro Recall": row["Macro Recall"],
        "Macro F1": row["Macro F1"]
    })


# Simple average
comparison_rows.append({
    "Model": "Average Ensemble",
    "Accuracy": avg_accuracy,
    "Macro Precision": avg_precision,
    "Macro Recall": avg_recall,
    "Macro F1": avg_f1
})


# Base
comparison_rows.append({
    "Model": "Base Ensemble",
    "Accuracy": base_accuracy,
    "Macro Precision": base_precision,
    "Macro Recall": base_recall,
    "Macro F1": base_f1
})


# HACE
comparison_rows.append({
    "Model": "HACE",
    "Accuracy": hace_accuracy,
    "Macro Precision": hace_precision,
    "Macro Recall": hace_recall,
    "Macro F1": hace_f1
})


comparison_df = pd.DataFrame(
    comparison_rows
).sort_values(
    "Macro F1",
    ascending=False
).reset_index(drop=True)


display(comparison_df)


print("\n" + "=" * 60)
print("HACE IMPROVEMENT")
print("=" * 60)

print(
    f"Base Macro F1 : {base_f1:.4f}"
)

print(
    f"HACE Macro F1 : {hace_f1:.4f}"
)

print(
    f"Improvement    : {hace_f1 - base_f1:+.4f}"
)

============================================================
MODEL COMPARISON
============================================================

              Model  Accuracy  Macro Precision  Macro Recall  Macro F1
0      finance_news  0.751691         0.752288      0.753311  0.749974
1              HACE  0.563700         0.629061      0.563616  0.547526
2     Base Ensemble  0.559372         0.630752      0.559121  0.540591
3        phrasebank  0.466324         0.622052      0.465990  0.423792
4  Average Ensemble  0.437111         0.530850      0.430188  0.393891
5              fiqa  0.413308         0.385146      0.407143  0.340612
6           twitter  0.304301         0.384581      0.301142  0.288609
7           general  0.225588         0.194720      0.221215  0.197428

============================================================
HACE IMPROVEMENT
============================================================
Base Macro F1 : 0.5406
HACE Macro F1 : 0.5475
Improvement    : +0.0069

In [55]:
from src.utils.config import config

print("Models directory:")
print(config.models_dir)

print("\nExists:", config.models_dir.exists())

for path in [
    config.models_dir / "fiqa",
    config.models_dir / "phrasebank",
    config.models_dir / "twitter",
    config.models_dir / "finance_news",
    config.models_dir / "general_finbert",
    config.models_dir / "meta_learner" / "hace_meta_learner.pkl",
]:
    print(path, "→", path.exists())

Models directory:
/content/HACE_Financial_Sentiment_Analysis/models

Exists: True
/content/HACE_Financial_Sentiment_Analysis/models/fiqa → False
/content/HACE_Financial_Sentiment_Analysis/models/phrasebank → False
/content/HACE_Financial_Sentiment_Analysis/models/twitter → False
/content/HACE_Financial_Sentiment_Analysis/models/finance_news → False
/content/HACE_Financial_Sentiment_Analysis/models/general_finbert → False
/content/HACE_Financial_Sentiment_Analysis/models/meta_learner/hace_meta_learner.pkl → True